### ISSUE TITLE
Instagram now serving 1440px images & some 1440x2650 stories

### ISSUE THREAD

**Issue by JCalv** [iHelp101/XInsta#100]
Xinsta is having some trouble. The image quality is dependent on the phone’s screen resolution. If you have a 1080p phone, then a 1080px image will be downloaded. If you have a 1440p phone, it will get a 1440px picture. Enabling the Force HR option in settings doesn't do anything in my experience. 
Auto-downloading is also inconsistent. Even on the 1440p phone it will get the 1080px images, while a manual download will get the hr 1440px

Here is an example of a 1440x2650 story from @mollycaitlynquinn https://i.imgur.com/rgw9W5b.jpg

And an example of a 1440p insta post  https://www.instagram.com/p/BxQUde8A6pe/

https://scontent-frt3-1.cdninstagram.com/vp/9f2a44a0c69e6686b4dd7f1bb29be29f/5D70D382/t51.2885-15/e35/60320703_465167720970645_7302803485499276975_n.jpg?_nc_ht=scontent-frt3-1.cdninstagram.com&se=7&ig_cache_key=MjA0MDIyMDYxODIxMzAxMDAxNA%3D%3D.2&ig_cache_prefix=full_size

Here is a git thread that may help  https://github.com/notcammy/PyInstaStories/issues/14

**Comment by iHelp101** [comment]
Fixed in next update.

**Comment by Poet145** [comment]
I see that this is closed, but I'd like to ask if this is necessary. I understand wanting the larger picture, but if we can only upload to IG at 1080x1350, isn't an "upscaled" image actually lesser quality? Can we now upload an image larger than 1080x1350?

**Comment by JCalv** [comment]
Yes and the quality of the 1440px images is in a lot of cases noticeably better when compared to the 1080px images. It's not just upscaling.

**Comment by Poet145** [comment]
Thanks for that information. This will change my own upload strategy :) I did not realize I could upload at a higher resolution than 1080. I mean, I knew I could, but assumed IG was reducing anything uploaded down to 1080 anyway. Uploading at 1440 from now on!
