### ISSUE TITLE
Story Privacy Hook Fails

### ISSUE THREAD

**Issue by skirol** [iHelp101/XInsta#101]
Story Privacy Hook hasn't been working for a while. At least since v76. 
Here's a log.
[Error.txt](https://github.com/iHelp101/XInsta/files/3171890/Error.txt)

**Comment by exodius48** [comment]
I confirmed this. Test on XInsta 2.1.0 , IG 93, TaiChi 5.2.0-232, MIUI 10  android 9, Device Poco F1
But download videos & image from strories work. @iHelp101 
[Error.txt](https://github.com/iHelp101/XInsta/files/3198253/Error.txt)

**Comment by iHelp101** [comment]
Fixed in next update.
