### ISSUE TITLE
[Help Wanted] Xinsta-Helper tool 

### ISSUE THREAD

**Issue by jizzy002** [iHelp101/XInsta#105]
After some time editing and fiddling around with the helper tool i managed to maybe create some hooks for newer instagram versions by comparing current class hooks

**example:** version: **1553740** has the **FeedOnClick** Class set to **X.5lh** 
which has this following string when opened with a text editor: _'story_app_attribution'_

I used your method from your python script " **grep -Ril 'story_app_attribution'** " to find are there anymore matches nor this _X.5lh class and there were none_ so i decompiled the lastest stable application and grepped through it's classes and there was only one **'story_app_attrubution'** match in a X class.

If you can review this, maybe the old hook finder could be used again?

[Xinsta-Helper (my respository)](https://github.com/jizzy002/Xinsta-Helper)
the only script i changed is findhooks.py and that's partially

**Comment by jizzy002** [comment]
Fully given up on this, not using xposed anymore.

**Comment by lol7344** [comment]
@jizzy002 Just out of curiosity - what are you using right now then? I am unable to find any working and updated enough version of Instagram that has photo/video download capabilities.
