### ISSUE TITLE
New Instagram Versions

### ISSUE THREAD

**Issue by iHelp101** [iHelp101/XInsta#109]
Please provide new Instagram versions that are not working. Beta and Alpha versions are difficult to support due to rapid changes. S

**Comment by Poet145** [comment]
I am currently running IG 101.0.0.15.120 on OnePlus 6T (Android 9) and none of the XInsta functions are working. I have updated the hooks through the UPDATE HOOKS section in the settings of XInsta from both Pastetbin and Github. I've also edited the hooks through the settings (Manually Change Hooks) by pasting from Pastebin. I've tried several versions, but I'm currently on build 1624390 and it does not work.

**Comment by 4F684D616E** [comment]
IG 98.0.0.15.119 (159526) 
LG V30 (Magisk + Xposed)
Android 8
None of the hooks are working and log is showing up as empty

**Comment by ayush7gl** [comment]
@ihelp101
IG 98.0.0.15.119 (159526) is the last version working with github hooks. Please update the hooks for IG 102.0.0.20.117.

**Comment by ayush7gl** [comment]
It's been a month, please update it to latest version @ihelp101

**Comment by exodius48** [comment]
android:versionCode="164094539"
android:versionName="103.1.0.15.119"

Hooks from pastebin & github can't be updated.
[Error.txt](https://github.com/iHelp101/XInsta/files/3433851/Error.txt)

Tested on Pocophone F1 android 9 MIUI 10

@iHelp101

**Comment by exodius48** [comment]
Download button not appear after successfully update hooks from pastebin.
@iHelp101 
[Error.txt](https://github.com/iHelp101/XInsta/files/3437955/Error.txt)

**Comment by adityashaw2** [comment]
Instagram version 92.0.0.15.114.
Even the "download" option is not shown in the App.
Android 7.1.2

**Comment by exodius48** [comment]
Instagram version 106.0.0.24.118 build 167338559 Download button disappear
[Error.txt](https://github.com/iHelp101/XInsta/files/3512715/Error.txt)
