### ISSUE TITLE
Instagram (115.0.0.26.11) It's working.

### ISSUE THREAD

**Issue by lacshire** [iHelp101/XInsta#112]
The latest version is working (Instagram 115.0.0.26.11), everything works well:
1. Download photos and videos from the feed and stories.
2. Download the profile image but in low quality.
The new version of instagram already brings the dark theme.

**Comment by lil-schemer** [comment]
Version code ?

**Comment by makeins29** [comment]
No funciona :(

**Comment by lacshire** [comment]
115.0.0.26.111 (177770663)
Link Apkmirror: https://www.apkmirror.com/apk/instagram/instagram-instagram/instagram-instagram-115-0-0-26-111-release/instagram-115-0-0-26-111-3-android-apk-download/

**Comment by makeins29** [comment]
On my Samsung with Android 7.0 it doesn't work for me :(

En mi Samsung con Android 7.0 no me funciona :(

**Comment by lol7344** [comment]
I used the "nodpi" version (build 177770652) and it works flawlessly.

**Instagram: 115.0.0.26.111
Build: 177770652
Arch: armeabi-v7a**

Download Link: https://www.apkmirror.com/apk/instagram/instagram-instagram/instagram-instagram-115-0-0-26-111-release/instagram-115-0-0-26-111-android-apk-download/
