### ISSUE TITLE
It seem you update code, can you release apk here please?!

### ISSUE THREAD

**Issue by hamedsbt** [iHelp101/XInsta#121]
Release apk here please...

**Comment by iHelp101** [comment]
If you would like to use the test APK it is linked below. I am trying to resolve video likes and profile icon issues before releasing a stable APK. 

https://drive.google.com/file/d/1MaBKcm6mFVimvo4ROgoR3pv59DYOfECa/view?usp=drivesdk

**Comment by exodius48** [comment]
> 
> 
> If you would like to use the test APK it is linked below. I am trying to resolve video likes and profile icon issues before releasing a stable APK.
> 
> https://drive.google.com/file/d/1MaBKcm6mFVimvo4ROgoR3pv59DYOfECa/view?usp=drivesdk

Im using this version along IG 123.0.0.21.114 build 188791674 https://www.apkmirror.com/apk/instagram/instagram-instagram/instagram-instagram-123-0-0-21-114-release/instagram-123-0-0-21-114-android-apk-download/

On my Poco F1 Android 10. Download button disappear. Updated hooks via pastebin.
