### ISSUE TITLE
help to find crait ver instagram

### ISSUE THREAD

**Issue by oops123456** [iHelp101/XInsta#123]
frist thank u about good apk work.

The version 19932599 was not found. I downloaded version 129.0.0.29.119 and did not work on it.

help me sr.

**Comment by iHelp101** [comment]
Can you provide your error log?

**Comment by oops123456** [comment]
٢٠٢٠٠٢٢٤_٠٢١٣٢٩ - XInsta Initialized
٢٠٢٠٠٢٢٤_٠٢١٣٢٩ - Instagram Version Code: 199325890
٢٠٢٠٠٢٢٤_٠٢١٣٢٩ - Device Codename: SM-N960F
٢٠٢٠٠٢٢٤_٠٢١٣٢٩ - Android Version: 9
٢٠٢٠٠٢٢٤_٠٢١٣٢٩ - XInsta Version 2.1.0
٢٠٢٠٠٢٢٤_٠٢١٣٣٠ - Dialog Hook Failed: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٢١٣٣٠ - Dialog Hook Class: X.1Qp
٢٠٢٠٠٢٢٤_٠٢١٣٣٠ - Direct OnClick Dialog Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٢١٣٣٠ - Mini Feed OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٢١٣٣٠ - Mini Feed Class Failed - X.000
٢٠٢٠٠٢٢٤_٠٢١٣٣٠ - Pin Press New Long Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.dl
٢٠٢٠٠٢٢٤_٠٢١٣٣٠ - Pin Press New Long Class - com.instagram.feed.r.a.dl
٢٠٢٠٠٢٢٤_٠٢١٣٣٠ - Profile Icon Click Listener Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٢١٣٣٠ - Profile Icon Click Listener Class - X.2cl
٢٠٢٠٠٢٢٤_٠٢١٣٣٠ - Other
٢٠٢٠٠٢٢٤_٠٢١٣٣٠ - Story Privacy Hook Failed - java.lang.NoSuchMethodError: com.instagram.reels.fragment.ReelViewerFragment#X.3F5(com.instagram.reels.fragment.ReelViewerFragment)#exact
٢٠٢٠٠٢٢٤_٠٢١٣٣٠ - Story Privacy Hook Class - com.instagram.reels.fragment.ReelViewerFragment
٢٠٢٠٠٢٢٤_٠٢١٣٣٠ - Story Privacy Hook Hook - X.3F5
٢٠٢٠٠٢٢٤_٠٢١٣٣٠ - Video Like Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٢١٣٣٠ - Video Like Class - X.2Rk
٢٠٢٠٠٢٢٤_٠٢١٣٤٦ - ---------------------------
٢٠٢٠٠٢٢٤_٠٢١٣٤٦ - XInsta Initialized
٢٠٢٠٠٢٢٤_٠٢١٣٤٦ - Instagram Version Code: 199325890
٢٠٢٠٠٢٢٤_٠٢١٣٤٦ - Device Codename: SM-N960F
٢٠٢٠٠٢٢٤_٠٢١٣٤٦ - Android Version: 9
٢٠٢٠٠٢٢٤_٠٢١٣٤٦ - XInsta Version 2.1.0
٢٠٢٠٠٢٢٤_٠٢١٣٤٧ - Dialog Hook Failed: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٢١٣٤٧ - Dialog Hook Class: X.1Qp
٢٠٢٠٠٢٢٤_٠٢١٣٤٧ - Direct OnClick Dialog Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٢١٣٤٧ - Mini Feed OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٢١٣٤٧ - Mini Feed Class Failed - X.000
٢٠٢٠٠٢٢٤_٠٢١٣٤٧ - Pin Press New Long Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.dl
٢٠٢٠٠٢٢٤_٠٢١٣٤٧ - Pin Press New Long Class - com.instagram.feed.r.a.dl
٢٠٢٠٠٢٢٤_٠٢١٣٤٧ - Profile Icon Click Listener Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٢١٣٤٧ - Profile Icon Click Listener Class - X.2cl
٢٠٢٠٠٢٢٤_٠٢١٣٤٨ - Other
٢٠٢٠٠٢٢٤_٠٢١٣٤٨ - Story Privacy Hook Failed - java.lang.NoSuchMethodError: com.instagram.reels.fragment.ReelViewerFragment#X.3F5(com.instagram.reels.fragment.ReelViewerFragment)#exact
٢٠٢٠٠٢٢٤_٠٢١٣٤٨ - Story Privacy Hook Class - com.instagram.reels.fragment.ReelViewerFragment
٢٠٢٠٠٢٢٤_٠٢١٣٤٨ - Story Privacy Hook Hook - X.3F5
٢٠٢٠٠٢٢٤_٠٢١٣٤٨ - Video Like Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٢١٣٤٨ - Video Like Class - X.2Rk
٢٠٢٠٠٢٢٤_٠٢١٥٠١ - ---------------------------
٢٠٢٠٠٢٢٤_٠٢١٥٠١ - XInsta Initialized
٢٠٢٠٠٢٢٤_٠٢١٥٠١ - Instagram Version Code: 199325890
٢٠٢٠٠٢٢٤_٠٢١٥٠١ - Device Codename: SM-N960F
٢٠٢٠٠٢٢٤_٠٢١٥٠١ - Android Version: 9
٢٠٢٠٠٢٢٤_٠٢١٥٠١ - XInsta Version 2.1.0
٢٠٢٠٠٢٢٤_٠٢١٥٠٢ - Dialog Hook Failed: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٢١٥٠٢ - Dialog Hook Class: X.1Qp
٢٠٢٠٠٢٢٤_٠٢١٥٠٢ - Direct OnClick Dialog Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٢١٥٠٢ - Mini Feed OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٢١٥٠٢ - Mini Feed Class Failed - X.000
٢٠٢٠٠٢٢٤_٠٢١٥٠٢ - Pin Press New Long Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.dl
٢٠٢٠٠٢٢٤_٠٢١٥٠٢ - Pin Press New Long Class - com.instagram.feed.r.a.dl
٢٠٢٠٠٢٢٤_٠٢١٥٠٢ - Profile Icon Click Listener Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٢١٥٠٢ - Profile Icon Click Listener Class - X.2cl
٢٠٢٠٠٢٢٤_٠٢١٥٠٣ - Other
٢٠٢٠٠٢٢٤_٠٢١٥٠٣ - Story Privacy Hook Failed - java.lang.NoSuchMethodError: com.instagram.reels.fragment.ReelViewerFragment#X.3F5(com.instagram.reels.fragment.ReelViewerFragment)#exact
٢٠٢٠٠٢٢٤_٠٢١٥٠٣ - Story Privacy Hook Class - com.instagram.reels.fragment.ReelViewerFragment
٢٠٢٠٠٢٢٤_٠٢١٥٠٣ - Story Privacy Hook Hook - X.3F5
٢٠٢٠٠٢٢٤_٠٢١٥٠٣ - Video Like Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٢١٥٠٣ - Video Like Class - X.2Rk
٢٠٢٠٠٢٢٤_٠٢٥١٤٦ - ---------------------------
٢٠٢٠٠٢٢٤_٠٢٥١٤٦ - XInsta Initialized
٢٠٢٠٠٢٢٤_٠٢٥١٤٦ - Instagram Version Code: 199325890
٢٠٢٠٠٢٢٤_٠٢٥١٤٦ - Device Codename: SM-N960F
٢٠٢٠٠٢٢٤_٠٢٥١٤٦ - Android Version: 9
٢٠٢٠٠٢٢٤_٠٢٥١٤٦ - XInsta Version 2.1.0
٢٠٢٠٠٢٢٤_٠٢٥١٤٧ - Dialog Hook Failed: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٢٥١٤٧ - Dialog Hook Class: X.1Qp
٢٠٢٠٠٢٢٤_٠٢٥١٤٧ - Direct OnClick Dialog Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٢٥١٤٧ - Mini Feed OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٢٥١٤٧ - Mini Feed Class Failed - X.000
٢٠٢٠٠٢٢٤_٠٢٥١٤٧ - Pin Press New Long Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.dl
٢٠٢٠٠٢٢٤_٠٢٥١٤٧ - Pin Press New Long Class - com.instagram.feed.r.a.dl
٢٠٢٠٠٢٢٤_٠٢٥١٤٧ - Profile Icon Click Listener Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٢٥١٤٧ - Profile Icon Click Listener Class - X.2cl
٢٠٢٠٠٢٢٤_٠٢٥١٤٧ - Other
٢٠٢٠٠٢٢٤_٠٢٥١٤٧ - Story Privacy Hook Failed - java.lang.NoSuchMethodError: com.instagram.reels.fragment.ReelViewerFragment#X.3F5(com.instagram.reels.fragment.ReelViewerFragment)#exact
٢٠٢٠٠٢٢٤_٠٢٥١٤٧ - Story Privacy Hook Class - com.instagram.reels.fragment.ReelViewerFragment
٢٠٢٠٠٢٢٤_٠٢٥١٤٧ - Story Privacy Hook Hook - X.3F5
٢٠٢٠٠٢٢٤_٠٢٥١٤٧ - Video Like Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٢٥١٤٧ - Video Like Class - X.2Rk
٢٠٢٠٠٢٢٤_٠٢٥١٤٩ - ---------------------------
٢٠٢٠٠٢٢٤_٠٢٥١٤٩ - XInsta Initialized
٢٠٢٠٠٢٢٤_٠٢٥١٤٩ - Instagram Version Code: 199325890
٢٠٢٠٠٢٢٤_٠٢٥١٤٩ - Device Codename: SM-N960F
٢٠٢٠٠٢٢٤_٠٢٥١٤٩ - Android Version: 9
٢٠٢٠٠٢٢٤_٠٢٥١٤٩ - XInsta Version 2.1.0
٢٠٢٠٠٢٢٤_٠٢٥١٤٩ - ---------------------------
٢٠٢٠٠٢٢٤_٠٢٥١٤٩ - XInsta Initialized
٢٠٢٠٠٢٢٤_٠٢٥١٤٩ - Instagram Version Code: 199325890
٢٠٢٠٠٢٢٤_٠٢٥١٤٩ - Device Codename: SM-N960F
٢٠٢٠٠٢٢٤_٠٢٥١٤٩ - Android Version: 9
٢٠٢٠٠٢٢٤_٠٢٥١٤٩ - XInsta Version 2.1.0
٢٠٢٠٠٢٢٤_٠٢٥١٤٩ - Dialog Hook Failed: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٢٥١٤٩ - Dialog Hook Class: X.1Qp
٢٠٢٠٠٢٢٤_٠٢٥١٤٩ - Direct OnClick Dialog Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٢٥١٤٩ - Mini Feed OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٢٥١٤٩ - Mini Feed Class Failed - X.000
٢٠٢٠٠٢٢٤_٠٢٥١٤٩ - Dialog Hook Failed: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٢٥١٤٩ - Dialog Hook Class: X.1Qp
٢٠٢٠٠٢٢٤_٠٢٥١٤٩ - Pin Press New Long Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.dl
٢٠٢٠٠٢٢٤_٠٢٥١٤٩ - Pin Press New Long Class - com.instagram.feed.r.a.dl
٢٠٢٠٠٢٢٤_٠٢٥١٤٩ - Profile Icon Click Listener Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٢٥١٤٩ - Profile Icon Click Listener Class - X.2cl
٢٠٢٠٠٢٢٤_٠٢٥١٤٩ - Direct OnClick Dialog Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٢٥١٤٩ - Other
٢٠٢٠٠٢٢٤_٠٢٥١٤٩ - Story Privacy Hook Failed - java.lang.NoSuchMethodError: com.instagram.reels.fragment.ReelViewerFragment#X.3F5(com.instagram.reels.fragment.ReelViewerFragment)#exact
٢٠٢٠٠٢٢٤_٠٢٥١٤٩ - Story Privacy Hook Class - com.instagram.reels.fragment.ReelViewerFragment
٢٠٢٠٠٢٢٤_٠٢٥١٤٩ - Story Privacy Hook Hook - X.3F5
٢٠٢٠٠٢٢٤_٠٢٥١٤٩ - Mini Feed OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٢٥١٤٩ - Mini Feed Class Failed - X.000
٢٠٢٠٠٢٢٤_٠٢٥١٤٩ - Video Like Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٢٥١٤٩ - Video Like Class - X.2Rk
٢٠٢٠٠٢٢٤_٠٢٥١٥٠ - Pin Press New Long Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.dl
٢٠٢٠٠٢٢٤_٠٢٥١٥٠ - Pin Press New Long Class - com.instagram.feed.r.a.dl
٢٠٢٠٠٢٢٤_٠٢٥١٥٠ - Profile Icon Click Listener Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٢٥١٥٠ - Profile Icon Click Listener Class - X.2cl
٢٠٢٠٠٢٢٤_٠٢٥١٥٠ - Other
٢٠٢٠٠٢٢٤_٠٢٥١٥٠ - Story Privacy Hook Failed - java.lang.NoSuchMethodError: com.instagram.reels.fragment.ReelViewerFragment#X.3F5(com.instagram.reels.fragment.ReelViewerFragment)#exact
٢٠٢٠٠٢٢٤_٠٢٥١٥٠ - Story Privacy Hook Class - com.instagram.reels.fragment.ReelViewerFragment
٢٠٢٠٠٢٢٤_٠٢٥١٥٠ - Story Privacy Hook Hook - X.3F5
٢٠٢٠٠٢٢٤_٠٢٥١٥٠ - Video Like Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٢٥١٥٠ - Video Like Class - X.2Rk
٢٠٢٠٠٢٢٤_٠٣٤٠١٨ - ---------------------------
٢٠٢٠٠٢٢٤_٠٣٤٠١٨ - XInsta Initialized
٢٠٢٠٠٢٢٤_٠٣٤٠١٨ - Instagram Version Code: 199325890
٢٠٢٠٠٢٢٤_٠٣٤٠١٨ - Device Codename: SM-N960F
٢٠٢٠٠٢٢٤_٠٣٤٠١٨ - Android Version: 9
٢٠٢٠٠٢٢٤_٠٣٤٠١٨ - XInsta Version 2.1.0
٢٠٢٠٠٢٢٤_٠٣٤٠١٩ - Dialog Hook Failed: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٣٤٠١٩ - Dialog Hook Class: X.1Qp
٢٠٢٠٠٢٢٤_٠٣٤٠١٩ - Direct OnClick Dialog Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٣٤٠٢٠ - Mini Feed OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٣٤٠٢٠ - Mini Feed Class Failed - X.000
٢٠٢٠٠٢٢٤_٠٣٤٠٢٠ - Pin Press New Long Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.dl
٢٠٢٠٠٢٢٤_٠٣٤٠٢٠ - Pin Press New Long Class - com.instagram.feed.r.a.dl
٢٠٢٠٠٢٢٤_٠٣٤٠٢٠ - Profile Icon Click Listener Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٣٤٠٢٠ - Profile Icon Click Listener Class - X.2cl
٢٠٢٠٠٢٢٤_٠٣٤٠٢٠ - Other
٢٠٢٠٠٢٢٤_٠٣٤٠٢٠ - Story Privacy Hook Failed - java.lang.NoSuchMethodError: com.instagram.reels.fragment.ReelViewerFragment#X.3F5(com.instagram.reels.fragment.ReelViewerFragment)#exact
٢٠٢٠٠٢٢٤_٠٣٤٠٢٠ - Story Privacy Hook Class - com.instagram.reels.fragment.ReelViewerFragment
٢٠٢٠٠٢٢٤_٠٣٤٠٢٠ - Story Privacy Hook Hook - X.3F5
٢٠٢٠٠٢٢٤_٠٣٤٠٢٠ - Video Like Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٣٤٠٢٠ - Video Like Class - X.2Rk
٢٠٢٠٠٢٢٤_٠٣٤٣٠٦ - ---------------------------
٢٠٢٠٠٢٢٤_٠٣٤٣٠٦ - XInsta Initialized
٢٠٢٠٠٢٢٤_٠٣٤٣٠٦ - Instagram Version Code: 199325890
٢٠٢٠٠٢٢٤_٠٣٤٣٠٦ - Device Codename: SM-N960F
٢٠٢٠٠٢٢٤_٠٣٤٣٠٦ - Android Version: 9
٢٠٢٠٠٢٢٤_٠٣٤٣٠٦ - XInsta Version 2.1.0
٢٠٢٠٠٢٢٤_٠٣٤٣٠٦ - Dialog Hook Failed: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٣٤٣٠٦ - Dialog Hook Class: X.1Qp
٢٠٢٠٠٢٢٤_٠٣٤٣٠٦ - Direct OnClick Dialog Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٣٤٣٠٦ - Mini Feed OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٣٤٣٠٦ - Mini Feed Class Failed - X.000
٢٠٢٠٠٢٢٤_٠٣٤٣٠٦ - Pin Press New Long Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.dl
٢٠٢٠٠٢٢٤_٠٣٤٣٠٦ - Pin Press New Long Class - com.instagram.feed.r.a.dl
٢٠٢٠٠٢٢٤_٠٣٤٣٠٧ - Profile Icon Click Listener Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٣٤٣٠٧ - Profile Icon Click Listener Class - X.2cl
٢٠٢٠٠٢٢٤_٠٣٤٣٠٧ - Other
٢٠٢٠٠٢٢٤_٠٣٤٣٠٧ - Story Privacy Hook Failed - java.lang.NoSuchMethodError: com.instagram.reels.fragment.ReelViewerFragment#X.3F5(com.instagram.reels.fragment.ReelViewerFragment)#exact
٢٠٢٠٠٢٢٤_٠٣٤٣٠٧ - Story Privacy Hook Class - com.instagram.reels.fragment.ReelViewerFragment
٢٠٢٠٠٢٢٤_٠٣٤٣٠٧ - Story Privacy Hook Hook - X.3F5
٢٠٢٠٠٢٢٤_٠٣٤٣٠٧ - Video Like Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٣٤٣٠٧ - Video Like Class - X.2Rk
20200224_034455 - X.3LB@3629a22;X.3LB
20200224_034455 - X.3LH@aa0959c;X.3LB
20200224_034455 - X.3LN@69d6ba5;X.3LB
20200224_034455 - X.3LB@3629a22;X.3LB
20200224_034455 - X.3LH@aa0959c;X.3LB
20200224_034455 - X.3LN@69d6ba5;X.3LB
20200224_034455 - X.3LB@3629a22;X.3LB
20200224_034455 - X.3LH@aa0959c;X.3LB
20200224_034455 - X.3LN@69d6ba5;X.3LB
20200224_034457 - X.3LB@3629a22;X.3LB
20200224_034457 - X.3LH@aa0959c;X.3LB
20200224_034457 - X.3LN@69d6ba5;X.3LB
20200224_034457 - X.3LB@3629a22;X.3LB
20200224_034457 - X.3LH@aa0959c;X.3LB
20200224_034457 - X.3LN@69d6ba5;X.3LB
٢٠٢٠٠٢٢٤_٠٣٤٥٠٧ - ---------------------------
٢٠٢٠٠٢٢٤_٠٣٤٥٠٧ - XInsta Initialized
٢٠٢٠٠٢٢٤_٠٣٤٥٠٧ - Instagram Version Code: 199325890
٢٠٢٠٠٢٢٤_٠٣٤٥٠٧ - Device Codename: SM-N960F
٢٠٢٠٠٢٢٤_٠٣٤٥٠٧ - Android Version: 9
٢٠٢٠٠٢٢٤_٠٣٤٥٠٧ - XInsta Version 2.1.0
٢٠٢٠٠٢٢٤_٠٣٤٥٠٨ - Dialog Hook Failed: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٣٤٥٠٨ - Dialog Hook Class: X.1Qp
٢٠٢٠٠٢٢٤_٠٣٤٥٠٨ - Direct OnClick Dialog Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٣٤٥٠٨ - Mini Feed OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٣٤٥٠٨ - Mini Feed Class Failed - X.000
٢٠٢٠٠٢٢٤_٠٣٤٥٠٨ - Pin Press New Long Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.dl
٢٠٢٠٠٢٢٤_٠٣٤٥٠٨ - Pin Press New Long Class - com.instagram.feed.r.a.dl
٢٠٢٠٠٢٢٤_٠٣٤٥٠٩ - Profile Icon Click Listener Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٣٤٥٠٩ - Profile Icon Click Listener Class - X.2cl
٢٠٢٠٠٢٢٤_٠٣٤٥٠٩ - Other
٢٠٢٠٠٢٢٤_٠٣٤٥٠٩ - Story Privacy Hook Failed - java.lang.NoSuchMethodError: com.instagram.reels.fragment.ReelViewerFragment#X.3F5(com.instagram.reels.fragment.ReelViewerFragment)#exact
٢٠٢٠٠٢٢٤_٠٣٤٥٠٩ - Story Privacy Hook Class - com.instagram.reels.fragment.ReelViewerFragment
٢٠٢٠٠٢٢٤_٠٣٤٥٠٩ - Story Privacy Hook Hook - X.3F5
٢٠٢٠٠٢٢٤_٠٣٤٥٠٩ - Video Like Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
٢٠٢٠٠٢٢٤_٠٣٤٥٠٩ - Video Like Class - X.2Rk

**Comment by oops123456** [comment]
> Can you provide your error log?
hi
i will weiting u sr.

**Comment by iHelp101** [comment]
Please try this APK. This is the latest test APK that should fix your issue.

https://drive.google.com/open?id=1MaBKcm6mFVimvo4ROgoR3pv59DYOfECa

**Comment by oops123456** [comment]
> Please try this APK. This is the latest test APK that should fix your issue.
> 
> https://drive.google.com/open?id=1MaBKcm6mFVimvo4ROgoR3pv59DYOfECa


Thank u bro its work.

**Comment by VARAA2** [comment]
### PERFECTLY WORKING VERSION
Instagram Version : **152.0.0.25.117**
Xinsta Version : **2.2.1**
with **updated Hooks**

_Oneplus 5T | Nougat_
