### ISSUE TITLE
Story Privacy doesn't work in latest versions of Instagram

### ISSUE THREAD

**Issue by mywalkb** [iHelp101/XInsta#127]
I'm testing the latest hooks. I developed a simple module xposed only for function Story Privacy.
I tested the version 145.0.0.32.119, 146.0.0.27.125 and 147.0.0.42.124 (for this version I found the class X.360).
This is the code that should not be invoked:

```
    public AnonymousClass0C0 A00;
    public final C57192ip A01;

    public final void A00() {
        C57192ip r0 = this.A01;
        if (r0 != null && !r0.A08.A06()) {
            C679035s r1 = this.A01.A08;
            C679035s A05 = r1.A05();
            r1.A04.clear();
            r1.A03.clear();
            r1.A05.clear();
            AnonymousClass1Rv A002 = AnonymousClass1Rv.A00(this.A00);
            if (!A05.A06()) {
                AnonymousClass1JE.A00(A002.A02).A03(A002.A0E(A05));
            }
        }
    }

    public AnonymousClass360(C57192ip r1, AnonymousClass0C0 r2) {
        this.A01 = r1;
        this.A00 = r2;
    }

```
but also if the code is not invoked the story is marked as seen.
Which version of Instagram has the story privacy working?

**Comment by iHelp101** [comment]
This setting makes it so Instagram does not report back to the story poster that you have seen the story. Your username will not be under the seen/viewers section of the poster's story.

**Comment by mywalkb** [comment]
Sorry my fault. I have developed some scripts php with famous project which use internal instagram's api, now removed.
With these scripts you can take info of stories for view them and mark as seen, if you want. I've always thought, seen = notification.
So you can see the story, mark as seen and if you want notification to the user you seen.
Sponsors are not hidden in the last two versions and I can't save posts, so I thought which also story privacy is not working, when I seen the story marked as seen.
