### ISSUE TITLE
Nothing works unfortunately. Am I using a wrong version? Error log attached 

### ISSUE THREAD

**Issue by VarunS2002** [iHelp101/XInsta#129]
[Error.txt](https://github.com/iHelp101/XInsta/files/5113855/Error.txt)

**Comment by iHelp101** [comment]
@ayush7gl Fixed the two hooks issues. I am looking into the profile icon issue. Instagram keeps changing the class this icon uses.

**Comment by ayush7gl** [comment]
@iHelp101 ads first show then disappear, story ads still showing. Story timer bug fixed

20200824_055212 - XInsta Initialized
20200824_055212 - Instagram Version Code: 239490565
20200824_055212 - Device Codename: POCOPHONE F1
20200824_055212 - Android Version: 10.0
20200824_055212 - XInsta Version 2.2.0
20200824_055212 - Mini Feed OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20200824_055212 - Mini Feed Class Failed - X.000
20200824_055212 - Pin Press New Long Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.dl
20200824_055212 - Pin Press New Long Class - com.instagram.feed.r.a.dl
20200824_055215 - ---------------------------
20200824_055215 - XInsta Initialized
20200824_055215 - Instagram Version Code: 239490565
20200824_055215 - Device Codename: POCOPHONE F1
20200824_055215 - Android Version: 10.0
20200824_055215 - XInsta Version 2.2.0
20200824_055215 - Mini Feed OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20200824_055215 - Mini Feed Class Failed - X.000
20200824_055215 - Pin Press New Long Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.dl
20200824_055215 - Pin Press New Long Class - com.instagram.feed.r.a.dl
20200824_055215 - ---------------------------
20200824_055215 - XInsta Initialized
20200824_055215 - Instagram Version Code: 239490565
20200824_055215 - Device Codename: POCOPHONE F1
20200824_055215 - Android Version: 10.0
20200824_055215 - XInsta Version 2.2.0
20200824_055216 - Mini Feed OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20200824_055216 - Mini Feed Class Failed - X.000
20200824_055216 - Pin Press New Long Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.dl
20200824_055216 - Pin Press New Long Class - com.instagram.feed.r.a.dl
20200824_055227 - X.34Y@2139efe;X.34Y
20200824_055227 - X.34p@a31d7f1;X.34Y
20200824_055227 - X.353@b7b022d;X.34Y
20200824_055227 - null;X.34Y
20200824_055227 - X.34Y@2139efe;X.34Y
20200824_055227 - X.34p@a31d7f1;X.34Y
20200824_055227 - X.353@b7b022d;X.34Y
20200824_055227 - null;X.34Y
20200824_055228 - X.34Y@2139efe;X.34Y
20200824_055228 - X.34p@a31d7f1;X.34Y
20200824_055228 - X.353@b7b022d;X.34Y
20200824_055228 - null;X.34Y
20200824_055228 - X.34Y@2139efe;X.34Y
20200824_055228 - X.34p@a31d7f1;X.34Y
20200824_055228 - X.353@b7b022d;X.34Y
20200824_055228 - null;X.34Y
20200824_055243 - X.34Y@a13c07e;X.34Y
20200824_055243 - X.34p@74321ad;X.34Y
20200824_055243 - X.353@a88a8cf;X.34Y
20200824_055243 - null;X.34Y
20200824_055244 - X.34Y@a13c07e;X.34Y
20200824_055244 - X.34p@74321ad;X.34Y
20200824_055244 - X.353@a88a8cf;X.34Y
20200824_055244 - null;X.34Y
20200824_055249 - X.34Y@2d4b605;X.34Y
20200824_055249 - X.34p@82bda67;X.34Y
20200824_055249 - X.353@268a0bd;X.34Y
20200824_055249 - null;X.34Y
20200824_055249 - X.34Y@2d4b605;X.34Y
20200824_055249 - X.34p@82bda67;X.34Y
20200824_055249 - X.353@268a0bd;X.34Y
20200824_055249 - null;X.34Y
20200824_055336 - X.34Y@92ea6ec;X.34Y
20200824_055336 - X.34p@d44e784;X.34Y
20200824_055336 - X.353@1ec73a2;X.34Y
20200824_055336 - null;X.34Y
20200824_055345 - X.34Y@52b74eb;X.34Y
20200824_055345 - X.34p@2b28af4;X.34Y
20200824_055345 - X.353@66f9663;X.34Y
20200824_055345 - null;X.34Y
20200824_055351 - X.34Y@c5c1f72;X.34Y
20200824_055351 - X.34p@528251f;X.34Y
20200824_055351 - X.353@345f635;X.34Y
20200824_055351 - null;X.34Y
20200824_055357 - X.34Y@d1600e3;X.34Y
20200824_055357 - X.34p@e9dc83f;X.34Y
20200824_055357 - X.353@2e71e55;X.34Y
20200824_055357 - null;X.34Y
20200824_055404 - X.34Y@d68cd7b;X.34Y
20200824_055404 - X.34p@32cc657;X.34Y
20200824_055404 - X.353@197c62d;X.34Y
20200824_055404 - null;X.34Y
20200824_055408 - X.34Y@5ffdbd5;X.34Y
20200824_055408 - X.34p@76f6051;X.34Y
20200824_055408 - X.353@5bd51b7;X.34Y
20200824_055408 - null;X.34Y
20200824_055414 - X.34Y@a703a78;X.34Y
20200824_055414 - X.34p@446c342;X.34Y
20200824_055414 - X.353@a1be090;X.34Y
20200824_055414 - null;X.34Y
20200824_055504 - X.34Y@3ccf248;X.34Y
20200824_055504 - X.34p@ec921d;X.34Y
20200824_055504 - X.353@5237663;X.34Y
20200824_055504 - X.34Y@3ccf248;X.34Y
20200824_055504 - X.34p@ec921d;X.34Y
20200824_055504 - X.353@5237663;X.34Y
20200824_055504 - X.34Y@3ccf248;X.34Y
20200824_055504 - X.34p@ec921d;X.34Y
20200824_055504 - X.353@5237663;X.34Y
20200824_055506 - X.34Y@3ccf248;X.34Y
20200824_055506 - X.34p@ec921d;X.34Y
20200824_055506 - X.353@5237663;X.34Y
20200824_055506 - null;X.34Y
20200824_055506 - X.34Y@3ccf248;X.34Y
20200824_055506 - X.34p@ec921d;X.34Y
20200824_055506 - X.353@5237663;X.34Y
20200824_055506 - null;X.34Y
20200824_055507 - X.34Y@3ccf248;X.34Y
20200824_055507 - X.34p@ec921d;X.34Y
20200824_055507 - X.353@5237663;X.34Y
20200824_055507 - null;X.34Y
20200824_055507 - X.34Y@3ccf248;X.34Y
20200824_055507 - X.34p@ec921d;X.34Y
20200824_055507 - X.353@5237663;X.34Y
20200824_055507 - null;X.34Y
20200824_055512 - X.34Y@1eaf24c;X.34Y
20200824_055512 - X.34p@c97b311;X.34Y
20200824_055512 - X.353@28ec277;X.34Y
20200824_055512 - X.34Y@1eaf24c;X.34Y
20200824_055512 - X.34p@c97b311;X.34Y
20200824_055512 - X.353@28ec277;X.34Y
20200824_055513 - X.34Y@1eaf24c;X.34Y
20200824_055513 - X.34p@c97b311;X.34Y
20200824_055513 - X.353@28ec277;X.34Y
20200824_055515 - X.34Y@915d4;X.34Y
20200824_055515 - X.34p@ef4679c;X.34Y
20200824_055515 - X.353@5266d7a;X.34Y
20200824_055515 - null;X.34Y
20200824_055515 - X.34Y@915d4;X.34Y
20200824_055515 - X.34p@ef4679c;X.34Y
20200824_055515 - X.353@5266d7a;X.34Y
20200824_055515 - null;X.34Y
20200824_055517 - X.34Y@915d4;X.34Y
20200824_055517 - X.34p@ef4679c;X.34Y
20200824_055517 - X.353@5266d7a;X.34Y
20200824_055517 - null;X.34Y
20200824_055517 - X.34Y@915d4;X.34Y
20200824_055517 - X.34p@ef4679c;X.34Y
20200824_055517 - X.353@5266d7a;X.34Y
20200824_055517 - null;X.34Y
20200824_055524 - X.34Y@348ddce;X.34Y
20200824_055524 - X.34p@8d2ce94;X.34Y
20200824_055524 - X.353@43fd932;X.34Y
20200824_055524 - X.34Y@348ddce;X.34Y
20200824_055524 - X.34p@8d2ce94;X.34Y
20200824_055524 - X.353@43fd932;X.34Y
20200824_055524 - X.34Y@348ddce;X.34Y
20200824_055524 - X.34p@8d2ce94;X.34Y
20200824_055524 - X.353@43fd932;X.34Y
20200824_055524 - X.34Y@348ddce;X.34Y
20200824_055524 - X.34p@8d2ce94;X.34Y
20200824_055524 - X.353@43fd932;X.34Y
20200824_055524 - X.34Y@348ddce;X.34Y
20200824_055524 - X.34p@8d2ce94;X.34Y
20200824_055524 - X.353@43fd932;X.34Y
20200824_055525 - X.34Y@348ddce;X.34Y
20200824_055525 - X.34p@8d2ce94;X.34Y
20200824_055525 - X.353@43fd932;X.34Y
20200824_055530 - X.34Y@deb3b15;X.34Y
20200824_055530 - X.34p@35d0ace;X.34Y
20200824_055530 - X.353@2521385;X.34Y
20200824_055530 - null;X.34Y
20200824_055542 - ExoPlayer
20200824_055722 - ---------------------------
20200824_055722 - XInsta Initialized
20200824_055722 - Instagram Version Code: 239490565
20200824_055722 - Device Codename: POCOPHONE F1
20200824_055722 - Android Version: 10.0
20200824_055722 - XInsta Version 2.2.0
20200824_055723 - Mini Feed OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20200824_055723 - Mini Feed Class Failed - X.000
20200824_055723 - Pin Press New Long Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.dl
20200824_055723 - Pin Press New Long Class - com.instagram.feed.r.a.dl
20200824_065246 - ---------------------------
20200824_065246 - XInsta Initialized
20200824_065246 - Instagram Version Code: 239490565
20200824_065246 - Device Codename: POCOPHONE F1
20200824_065246 - Android Version: 10.0
20200824_065246 - XInsta Version 2.2.0
20200824_065246 - Mini Feed OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20200824_065246 - Mini Feed Class Failed - X.000
20200824_065246 - Pin Press New Long Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.dl
20200824_065246 - Pin Press New Long Class - com.instagram.feed.r.a.dl
20200824_065248 - ---------------------------
20200824_065248 - XInsta Initialized
20200824_065248 - Instagram Version Code: 239490565
20200824_065248 - Device Codename: POCOPHONE F1
20200824_065248 - Android Version: 10.0
20200824_065248 - XInsta Version 2.2.0
20200824_065248 - Mini Feed OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20200824_065248 - Mini Feed Class Failed - X.000
20200824_065248 - Pin Press New Long Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.dl
20200824_065248 - Pin Press New Long Class - com.instagram.feed.r.a.dl
20200824_065248 - ---------------------------
20200824_065248 - XInsta Initialized
20200824_065248 - Instagram Version Code: 239490565
20200824_065248 - Device Codename: POCOPHONE F1
20200824_065248 - Android Version: 10.0
20200824_065248 - XInsta Version 2.2.0
20200824_065249 - Mini Feed OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20200824_065249 - Mini Feed Class Failed - X.000
20200824_065249 - Pin Press New Long Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.dl
20200824_065249 - Pin Press New Long Class - com.instagram.feed.r.a.dl
20200824_065303 - ExoPlayer
20200824_065542 - ---------------------------
20200824_065542 - XInsta Initialized
20200824_065542 - Instagram Version Code: 239490565
20200824_065542 - Device Codename: POCOPHONE F1
20200824_065542 - Android Version: 10.0
20200824_065542 - XInsta Version 2.2.0
20200824_065542 - Mini Feed OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20200824_065542 - Mini Feed Class Failed - X.000
20200824_065543 - Pin Press New Long Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.dl
20200824_065543 - Pin Press New Long Class - com.instagram.feed.r.a.dl
20200824_065545 - ExoPlayer
20200824_065552 - ExoPlayer
20200824_070702 - ---------------------------
20200824_070702 - XInsta Initialized
20200824_070702 - Instagram Version Code: 239490565
20200824_070702 - Device Codename: POCOPHONE F1
20200824_070702 - Android Version: 10.0
20200824_070702 - XInsta Version 2.2.0
20200824_070702 - Mini Feed OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20200824_070702 - Mini Feed Class Failed - X.000
20200824_070702 - Pin Press New Long Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.dl
20200824_070702 - Pin Press New Long Class - com.instagram.feed.r.a.dl
20200824_070830 - ExoPlayer
20200824_070831 - ---------------------------
20200824_070831 - XInsta Initialized
20200824_070831 - Instagram Version Code: 239490565
20200824_070831 - Device Codename: POCOPHONE F1
20200824_070831 - Android Version: 10.0
20200824_070831 - XInsta Version 2.2.0
20200824_070831 - Mini Feed OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20200824_070831 - Mini Feed Class Failed - X.000
20200824_070831 - Pin Press New Long Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.dl
20200824_070831 - Pin Press New Long Class - com.instagram.feed.r.a.dl
20200824_070900 - ExoPlayer

**Comment by VarunS2002** [comment]
> I just pushed a hook update for the latest Instagram release (Stable). I also pushed XInsta 2.2.0 out since it was long overdue. I have the auto decompiler working better now with only 10-ish manual hooks compared to the previous 48. I will try to devote more time to this project. I work full time and am going for my Master's degree as well, so I am more limited on time than I once was. - William

Keep up the good work man all the best. But can you please tell me the exact version number of instagram which works because latest version differs by country some times on play store

**Comment by ayush7gl** [comment]
> > I just pushed a hook update for the latest Instagram release (Stable). I also pushed XInsta 2.2.0 out since it was long overdue. I have the auto decompiler working better now with only 10-ish manual hooks compared to the previous 48. I will try to devote more time to this project. I work full time and am going for my Master's degree as well, so I am more limited on time than I once was. - William
> 
> Keep up the good work man all the best. But can you please tell me the exact version number of instagram which works because latest version differs by country some times on play store

https://www.apkmirror.com/apk/instagram/instagram-instagram/instagram-instagram-155-0-0-37-107-release/

This is the latest version supported. You can also follow xda page to know about update and supported versions

https://forum.xda-developers.com/xposed/modules/mod-xinsta-download-images-videos-t3077110/page675

**Comment by VarunS2002** [comment]
> > > I just pushed a hook update for the latest Instagram release (Stable). I also pushed XInsta 2.2.0 out since it was long overdue. I have the auto decompiler working better now with only 10-ish manual hooks compared to the previous 48. I will try to devote more time to this project. I work full time and am going for my Master's degree as well, so I am more limited on time than I once was. - William
> > 
> > 
> > Keep up the good work man all the best. But can you please tell me the exact version number of instagram which works because latest version differs by country some times on play store
> 
> https://www.apkmirror.com/apk/instagram/instagram-instagram/instagram-instagram-155-0-0-37-107-release/
> 
> This is the latest version supported. You can also follow xda page to know about update and supported versions
> 
> https://forum.xda-developers.com/xposed/modules/mod-xinsta-download-images-videos-t3077110/page675

Thank you very much. A suggestion to add a label for specifying the supported instagram version in the app or in the first line of hooks.txt.
