### ISSUE TITLE
What makes the latest APK 1100% bigger in size?

### ISSUE THREAD

**Issue by Shivelight** [iHelp101/XInsta#130]
I notice the latest APK 5d6dd9c3a5415fc25ba4f638c3dd67b461438879 is so big compared to older release. How is this?

EDIT: Title. More accurate percentage lol

**Comment by iHelp101** [comment]
This was a update to live stories and muxing. Live Stories require the audio and video to be combined, which I originally used mp4parser for. The library had some reliability issues so I moved to FFMPEG, which sadly is quite a big library even when using the minimal build.

**Comment by Shivelight** [comment]
I actually notice the FFMPEG library after posting this issue but still don't know what it is for since the last code update was few months ago. So that means we can download live stories? That's new to me.

As a feedback, the latest APK is more stable and almost everything I need works correctly except the disable story timer option which keep crashing instagram everytime I open a story. I'm using instagram version 152.0.0.25.117 (234847229), not a big deal tho. Overall it's awesome!

**Comment by iHelp101** [comment]
You can download Live Stories once they are posted to a user's story. So in theory they are no longer live, but they still follow the same elements of an XML file with contents that need to be muxed. I am looking at the story timer crash now.

**Comment by iHelp101** [comment]
I updated the hooks to fix this crash. Please open XInsta -> Click Pastebin or GitHub and reboot. Thank you.

**Comment by Shivelight** [comment]
Thank you 👍
