### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by geramnya** [iHelp101/XInsta#14]
Make change color in following list

**Comment by iHelp101** [comment]
Can you explain this a little more?

**Comment by geramnya** [comment]
I mean for follow indicator already exist but need to add some like that in tab me-->following(change colour for who have follow back)..if not understand give me email and i will sent screenshot😁

**Comment by iHelp101** [comment]
I looked into this. At the moment this is not appearing possible due to how Instagram stores this information. The tag "followed_by" is not currently in the user class, which means it's can't be references to know if a user follows you back. I will look some more, but no promises.

**Comment by iHelp101** [comment]
I have spent a good amount of time trying to get this working. Due to current limitations this is not possible.
