### ISSUE TITLE
profile picture download

### ISSUE THREAD

**Issue by bramdsgn** [iHelp101/XInsta#15]
Downloading profile pictures not working anymore, they made some changes. Now you need to remove the "vp/" part, and change the size to "s1080x1080" or "s720x720" can you make an update?

**Comment by iHelp101** [comment]
I have a fix for this already. I will be releasing XInsta 2.0 shortly. I am waiting on some final feedback from some testers. The way XInsta handles these post is by removed /vp/ and the URL hashes. An example is below.

https://scontent-mia3-2.cdninstagram.com/vp/4d7fa77be16a8f5feabdaa481cfd6639/5B21CAE8/t51.2885-19/s150x150/13597791_261499887553333_1855531912_a.jpg

https://scontent-mia3-2.cdninstagram.com/t51.2885-19/13597791_261499887553333_1855531912_a.jpg

**Comment by bramdsgn** [comment]
Even better, 
Can't wait :)

**Comment by iHelp101** [comment]
Resolved In XInsta 2.0.0.
