### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by maharshi22397** [iHelp101/XInsta#16]
can you add feature for privacy in chats eg.
if you send any person a photo it shows like delivered , opened, captured screen shot.
i mean if i take screen shot of that photo then it shows sender that a screen shot was taken.
![inkedscreenshot_20180201-125707_li](https://user-images.githubusercontent.com/36028327/35666565-93c43018-0750-11e8-818d-4b535f2cefe2.jpg)

**Comment by iHelp101** [comment]
I will look into it. With direct messages/chats you can long press an image and download it, so a screenshot is not required. I will look into blocking status updated of delivered, opened, etc.

**Comment by iHelp101** [comment]
I have added hooks to block the screenshot detection. Statuses can not be hooked. Instagram updates the status when an image/video is fetched. This is server side.
