### ISSUE TITLE
Hide discover section

### ISSUE THREAD

**Issue by koko-ng** [iHelp101/XInsta#17]
It could be a nice feature to remove the discover section, or just to keep the search bar. Honestly, I just keep losing my time scrolling this section.

**Comment by iHelp101** [comment]
Can you attach a screenshot with the items you would like removed circled or highlighted?

**Comment by iHelp101** [comment]
I linkee an example screenshot. Is this the desired results? Please excuse the small areas that were not cover up white. 

https://i.imgur.com/6Skbwi4.png

**Comment by koko-ng** [comment]
Exactly, thanks. Maybe you could switch directly to the view when we press on the search bar? As it was, if I remember well, before the discover section was introduced.

**Comment by iHelp101** [comment]
Your requested feature has been added to the module. It will be in the next update. I will work on adding it to the hooks shortly and get the hook complete. An example of the hook in progress is below.


XposedHelpers.findAndHookMethod("com.instagram.explore.m.bc", lpparam.classLoader, "onCreateView", LayoutInflater.class, ViewGroup.class, Bundle.class, new XC_MethodHook() {
                @Override
                protected void afterHookedMethod(MethodHookParam param) throws Throwable {
                    super.afterHookedMethod(param);
                    if (Helper.getSettings("DiscoverHide")) {
                        FrameLayout frameLayout = (FrameLayout) param.getResult();
                        frameLayout.setVisibility(View.GONE);
                    }
                }
            });
