### ISSUE TITLE
Sponsored no longer blocked

### ISSUE THREAD

**Issue by dubyadud** [iHelp101/XInsta#18]
Instagram's "Sponsored" posts are no longer removed from feed.  Any chance you can fix this feature?  As-is, Instagram has way too damn many of these sponsor ads.

**Comment by iHelp101** [comment]
Please attach your Xposed error log. I am not aware of any hooks issues related to sponsored post.

**Comment by dubyadud** [comment]
https://drive.google.com/file/d/1u26u32i47o2RvbFUE6MjC2y1xpyjUvlX/view?usp=drivesdk

**Comment by iHelp101** [comment]
Your Xposed error log for some reason is full of random symbols. Can you instead open XInsta -> Three Line Icon -> Send Error Log. That should give a cleaner log.

**Comment by dubyadud** [comment]
Sorry about that:
https://drive.google.com/file/d/1P0wk0S1nX96TYE-z5F8VOcRM2QXK68fE/view?usp=drivesdk

**Comment by iHelp101** [comment]
I just tested this exact version you are on and I am having no issues with sponsored post. Are you seeing paid sponsorships maybe (Brand deals with users for example)?

**Comment by dubyadud** [comment]
https://i.imgur.com/V6SvqBp.png

Perhaps I just didn't notice them before, or wasn't getting them?  If these are not blocked now; can it he implemented?

**Comment by iHelp101** [comment]
Okay, I am looking into this more. These are normally blocked. One thing to note is the first sponsored post is sometimes not blocked or has only parts of it blocked. This is due to how Instagram loads content (Not fully loaded until in focus).

**Comment by dubyadud** [comment]
I have several of these in my feed too.  Thanks for looking into it!

**Comment by iHelp101** [comment]
Can you please uninstall XInsta, reboot, install XInsta, and reboot once more? I can't seem to find any other reason sponsored post are not hidden besides an upgrade issue (1.9.99 to 2.0.0).

**Comment by dubyadud** [comment]
1.9.99 works
