### ISSUE TITLE
How to get old date formatting? 

### ISSUE THREAD

**Issue by x0x0x0x0** [iHelp101/XInsta#19]
In the latest version I believe date formatting was added. Thing is I would like to see the x hours ago instead of an exact time, is there any way to switch between the exact time and the hrs ago?

**Comment by iHelp101** [comment]
When changing the setting activity I did not add an option to disable this by accident. It will be fixed in the next update. Please open /storage/emulated/0/.Instagram/ with a file browser and delete the Date.txt file.

**Comment by x0x0x0x0** [comment]
Alright, thank you!
