### ISSUE TITLE
Missing download button for pictures andere video's, insta stories do work

### ISSUE THREAD

**Issue by SonnyX** [iHelp101/XInsta#2]
20160904_141621 - XInsta Initialized
20160904_141621 - Instagram Version Code: 37734557
20160904_141621 - Device Codename: SM-G900F
20160904_141621 - Android Version: 6.0.1
20160904_141621 - XInsta Version 1.7.4
20160904_141621 - Media Options Button Hook Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20160904_141621 - Trying New Push Notification Method

**Comment by iHelp101** [comment]
You need to update to XInsta 1.7.6.

**Comment by SonnyX** [comment]
Worked like a charm, thanks!
Somehow versions 1.7.5 and 1.7.6 didn't show up (and still doesn't for me) in xposed installer.
