### ISSUE TITLE
Downloading and Settings not work 

### ISSUE THREAD

**Issue by acsway878787** [iHelp101/XInsta#22]
Tried to download videos and photos, and both failed.
By the way, the switches in Settings couldn't be turned on properly. If I turn something on then return back to main menu of XInsta, the options I changed will be reverted back to defaults. However, this doesn't happen on all of the options, some works well, like "Hide Download Notification For Completed Download" , some turns out buggy, such as "Tap Comments To Copy".

Here are the error log and device information:
> 20180323_112540- XInsta Initialized
20180323_112540 - Instagram Version Code: 98288242
20180323_112540 - Device Codename: ASUS_T00N
20180323_112540 - Android Version: 4.4.2
20180323_112540 - XInsta Version 2.0.2
20180323_112557 - Falling Back To New Video Method
20180323_112557 - Switch Link - Different Media Type
20180323_112559 - Falling Back To New Video Method
20180323_112559 - Switch Link - Different Media Type
20180323_112559 - Falling Back To New Video Method
20180323_112600 - Download Error - java.io.FileNotFoundException: https://scontent-tpe1-1.cdninstagram.com/t51.2885-15/e35/29090671_172791770109174_1818953679609266176_n.jpg?se=7&ig_cache_key=MTczOTg1MjM2Mjc3ODc0MjE5Ng%3D%3D.2&ig_cache_prefix=full_size_&ig_cache_prefix=full_size_
20180323_112600 - Download Error - java.io.FileNotFoundException: https://scontent-tpe1-1.cdninstagram.com/t50.2886-16/29013741_439988596421231_7098765156551755481_n.mp4

**Comment by stevesbrain** [comment]
Same issue here

**Comment by iHelp101** [comment]
I am working on this issue. If you click a URL from your error log you will see Access Denied. Instagram is enforcing URL signatures, which is causing issues for XInsta. I have a fix, but that fix does not allow full resolution downloads for all users. The URL Instagram provides is dependent on the device.
