### ISSUE TITLE
Can't download photos and videos with any version of Instagram Alpha or Beta

### ISSUE THREAD

**Issue by LuneWalsh** [iHelp101/XInsta#23]
Please check out my XInsta Error Log.

k5MQ%3D%3D.2&ig_cache_prefix=full_size_
20180323_010552 - Falling Back To New Video Method
20180323_010552 - Download Error - java.io.FileNotFoundException: https://instagram.fgru7-1.fna.fbcdn.net/t50.2886-16/29013262_1645430875504342_1192808410618265600_n.mp4
20180323_010555 - Falling Back To New Video Method
20180323_010555 - Switch Link - Different Media Type
20180323_010556 - Download Error - java.io.FileNotFoundException: https://instagram.fgru7-1.fna.fbcdn.net/t51.2885-15/e35/28764365_219167428825982_5663349988244062208_n.jpg?se=7&ig_cache_key=MTc0MDE5MDUyNDA1MTQ3ODU2OQ%3D%3D.2&ig_cache_prefix=full_size_
20180323_010901 - ---------------------------
20180323_010901 - XInsta Initialized
20180323_010901 - Instagram Version Code: 98766551
20180323_010901 - Device Codename: ASUS_Z012DC
20180323_010901 - Android Version: 8.0.0
20180323_010901 - XInsta Version 2.0.2
20180323_010901 - Hooks Fetched!
20180323_010902 - ---------------------------
20180323_010902 - XInsta Initialized
20180323_010902 - Instagram Version Code: 98766551
20180323_010902 - Device Codename: ASUS_Z012DC
20180323_010902 - Android Version: 8.0.0
20180323_010902 - XInsta Version 2.0.2
20180323_010903 - Hooks Fetched!
20180323_010907 - ---------------------------
20180323_010907 - XInsta Initialized
20180323_010907 - Instagram Version Code: 98766551
20180323_010907 - Device Codename: ASUS_Z012DC
20180323_010907 - Android Version: 8.0.0
20180323_010907 - XInsta Version 2.0.2
20180323_010907 - Hooks Fetched!
20180323_011521 - ---------------------------
20180323_011521 - XInsta Initialized
20180323_011521 - Instagram Version Code: 98766551
20180323_011521 - Device Codename: ASUS_Z012DC
20180323_011521 - Android Version: 8.0.0
20180323_011521 - XInsta Version 2.0.2
20180323_011521 - Falling Back On Older Hooks
20180323_011524 - Falling Back To New Video Method
20180323_011524 - Switch Link - Different Media Type
20180323_011524 - Download Error - java.io.FileNotFoundException: https://instagram.fgru7-1.fna.fbcdn.net/t51.2885-15/e35/29417455_420443925068583_4729173255376601088_n.jpg?ig_cache_key=MTc0MDY0ODIxOTEyODg2NzEwOA%3D%3D.2&ig_cache_prefix=full_size_
20180323_011537 - ---------------------------
20180323_011537 - XInsta Initialized
20180323_011537 - Instagram Version Code: 98766551
20180323_011537 - Device Codename: ASUS_Z012DC
20180323_011537 - Android Version: 8.0.0
20180323_011537 - XInsta Version 2.0.2
20180323_011538 - Hooks Fetched!
20180323_011539 - ---------------------------
20180323_011539 - XInsta Initialized
20180323_011539 - Instagram Version Code: 98766551
20180323_011539 - Device Codename: ASUS_Z012DC
20180323_011539 - Android Version: 8.0.0
20180323_011539 - XInsta Version 2.0.2
20180323_011539 - Hooks Fetched!
20180323_011714 - ---------------------------
20180323_011714 - XInsta Initialized
20180323_011714 - Instagram Version Code: 98766551
20180323_011714 - Device Codename: ASUS_Z012DC
20180323_011714 - Android Version: 8.0.0
20180323_011714 - XInsta Version 2.0.2
20180323_011714 - Hooks Fetched!
20180323_011718 - Falling Back To New Video Method
20180323_011718 - Switch Link - Different Media Type
20180323_011718 - Download Error - java.io.FileNotFoundException: https://instagram.fgru7-1.fna.fbcdn.net/t51.2885-15/e35/29093724_2032479733637100_5836114570984292352_n.jpg?se=7&ig_cache_key=MTczOTk2NjY5NzA5ODgwMzQ1Mg%3D%3D.2&ig_cache_prefix=full_size_

03-23 01:17:14.547 I/Xposed  (24747): XInsta - XInsta Initialized
03-23 01:17:14.556 I/Xposed  (24747): XInsta - Instagram Version Code: 98766551
03-23 01:17:14.559 I/Xposed  (24747): XInsta - Device Codename: ASUS_Z012DC
03-23 01:17:14.562 I/Xposed  (24747): XInsta - Android Version: 8.0.0
03-23 01:17:14.566 I/Xposed  (24747): XInsta - XInsta Version 2.0.2
03-23 01:17:14.946 I/Xposed  (24747): XInsta - Hooks Fetched!
03-23 01:17:18.421 I/Xposed  (24269): XInsta - Falling Back To New Video Method
03-23 01:17:18.427 I/Xposed  (24269): XInsta - Switch Link - Different Media Type

Fix this please, yesterday the mod still works fine, now I can't download anything.

**Comment by stevesbrain** [comment]
Can confirm, the same happens here (only since today, yesterday was fine)

**Comment by yanfedorov** [comment]
same problem

**Comment by iHelp101** [comment]
I am working on this issue. Instagram is enforcing URL signatures, which break downloads that attempt to download full resolution images/videos.

**Comment by ibnux** [comment]
It doesn't matter for short time to update it with standard resolution download.
If it still cannot get the highest quality

**Comment by stevesbrain** [comment]
Thanks @ihelp101 - much appreciate your work :)

**Comment by brato-mo** [comment]
Still i cant download...fix it please

**Comment by stevesbrain** [comment]
@brato-mo It was fixed; update your plugin :)
