### ISSUE TITLE
I can not download anything, why is this error? 

### ISSUE THREAD

**Issue by marcosfiniano** [iHelp101/XInsta#24]
Since yesterday is not working, please can fix this error

**Comment by marcosfiniano** [comment]
13:55:14.522 I/Xposed  (19789): XInsta - Android Version: 8.0.0
03-23 13:55:14.546 I/Xposed  (19789): XInsta - XInsta Version 2.0.2
03-23 13:55:15.384 I/Xposed  (19789): XInsta - Discovery Class Failed - java.lang.NullPointerException: className must not be null.
03-23 13:55:15.411 I/Xposed  (19789): XInsta - Discovery Class - null
03-23 13:55:15.440 I/Xposed  (19789): XInsta - Liked Post Failed - java.lang.NullPointerException: className must not be null.
03-23 13:55:15.467 I/Xposed  (19789): XInsta - Liked Post Class - null

**Comment by iHelp101** [comment]
This is due to a signature URL change by Instagram. It is causing downloads to fail. I am working on a solution.

**Comment by marcosfiniano** [comment]
thank you for taking your time, I appreciate your attention

**Comment by Piyushyadav30** [comment]
Cannot download the images and videos from Instagram do something help me after the last update
