### ISSUE TITLE
Bad image/video quality after enabling xinsta

### ISSUE THREAD

**Issue by FinnMartinz** [iHelp101/XInsta#30]
I got all my images and videos from Instgram feed blurred and pixled right after enabling Xinsta, So surely Xinsta is involved in making this bug occur.
How do I solve that?

**Comment by iHelp101** [comment]
Did you enable the force high resolution feature? This feature can cause issues on certain devices.

**Comment by FinnMartinz** [comment]
I found that the feature itself is what caused the blurred images at first place. Images as well as videos are way better without it.
