### ISSUE TITLE
Download button missing again 

### ISSUE THREAD

**Issue by LuneWalsh** [iHelp101/XInsta#31]
04-10 01:22:57.294 ?/SENTINEL_TAG( 9992): SENTINEL_MSG_LIBCUTILS
04-10 01:22:57.294 ?/SENTINEL_TAG( 9992): SENTINEL_MSG_LIBLOG
04-10 01:22:57.602 I/Xposed  (10040): XInsta - XInsta Initialized
04-10 01:22:57.616 I/Xposed  (10040): XInsta - Instagram Version Code: 102223529
04-10 01:22:57.620 I/Xposed  (10040): XInsta - Device Codename: ASUS_Z012DC
04-10 01:22:57.627 I/Xposed  (10040): XInsta - Android Version: 8.0.0
04-10 01:22:57.644 I/Xposed  (10040): XInsta - XInsta Version 2.0.4
04-10 01:22:59.457 I/Xposed  (10040): XInsta - Hooks Fetched!
04-10 01:22:59.894 I/Xposed  (10040): XInsta - Comment Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.comments.e.o
04-10 01:22:59.898 I/Xposed  (10040): XInsta - Comment Class: com.instagram.feed.comments.e.o
04-10 01:22:59.913 I/Xposed  (10040): XInsta - Direct Private Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
04-10 01:22:59.921 I/Xposed  (10040): XInsta - Menu Click Listener Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
04-10 01:22:59.945 I/Xposed  (10040): XInsta - Profile Icon Click Listener Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
04-10 01:22:59.949 I/Xposed  (10040): XInsta - Profile Icon Click Listener Class - com.instagram.profile.fragment.fx
04-10 01:22:59.961 I/Xposed  (10040): XInsta - Search Tag Hook Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.v.b.b.b
04-10 01:22:59.967 I/Xposed  (10040): XInsta - Search Location Hook Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.v.b.d.d
04-10 01:22:59.974 I/Xposed  (10040): XInsta - Search Username Hook Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.v.a.c.b
04-10 01:22:59.980 I/Xposed  (10040): XInsta - Search Top Hook Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.v.b.e.m
04-10 01:22:59.985 I/Xposed  (10040): XInsta - Share Class Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
04-10 01:22:59.988 I/Xposed  (10040): XInsta - Share Class - com.instagram.feed.q.b.ad
04-10 01:23:00.590 I/Xposed  (10116): XInsta - XInsta Initialized
04-10 01:23:00.607 I/Xposed  (10116): XInsta - Instagram Version Code: 102223529
04-10 01:23:00.613 I/Xposed  (10116): XInsta - Device Codename: ASUS_Z012DC
04-10 01:23:00.618 I/Xposed  (10116): XInsta - Android Version: 8.0.0
04-10 01:23:00.622 I/Xposed  (10116): XInsta - XInsta Version 2.0.4
04-10 01:23:00.934 I/Xposed  (10116): XInsta - Hooks Fetched!
04-10 01:23:01.142 ?/SENTINEL_TAG(10172): SENTINEL_MSG_LIBCUTILS
04-10 01:23:01.142 ?/SENTINEL_TAG(10172): SENTINEL_MSG_LIBLOG
04-10 01:23:01.420 I/Xposed  (10116): XInsta - Comment Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.comments.e.o
04-10 01:23:01.425 I/Xposed  (10116): XInsta - Comment Class: com.instagram.feed.comments.e.o
04-10 01:23:01.456 I/Xposed  (10116): XInsta - Direct Private Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
04-10 01:23:01.469 I/Xposed  (10116): XInsta - Menu Click Listener Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
04-10 01:23:01.505 I/Xposed  (10116): XInsta - Profile Icon Click Listener Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
04-10 01:23:01.512 I/Xposed  (10116): XInsta - Profile Icon Click Listener Class - com.instagram.profile.fragment.fx
04-10 01:23:01.530 I/Xposed  (10116): XInsta - Search Tag Hook Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.v.b.b.b
04-10 01:23:01.537 I/Xposed  (10116): XInsta - Search Location Hook Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.v.b.d.d
04-10 01:23:01.547 I/Xposed  (10116): XInsta - Search Username Hook Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.v.a.c.b
04-10 01:23:01.555 I/Xposed  (10116): XInsta - Search Top Hook Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.v.b.e.m
04-10 01:23:01.561 I/Xposed  (10116): XInsta - Share Class Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
04-10 01:23:01.565 I/Xposed  (10116): XInsta - Share Class - com.instagram.feed.q.b.ad
04-10 01:23:01.900 I/Xposed  (10283): XInsta - XInsta Initialized
04-10 01:23:01.921 I/Xposed  (10283): XInsta - Instagram Version Code: 102223529
04-10 01:23:01.927 I/Xposed  (10283): XInsta - Device Codename: ASUS_Z012DC
04-10 01:23:01.934 I/Xposed  (10283): XInsta - Android Version: 8.0.0
04-10 01:23:01.940 I/Xposed  (10283): XInsta - XInsta Version 2.0.4
04-10 01:23:02.333 I/Xposed  (10283): XInsta - Hooks Fetched!
04-10 01:23:02.839 I/Xposed  (10283): XInsta - Comment Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.comments.e.o
04-10 01:23:02.845 I/Xposed  (10283): XInsta - Comment Class: com.instagram.feed.comments.e.o
04-10 01:23:02.861 I/Xposed  (10283): XInsta - Direct Private Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
04-10 01:23:02.869 I/Xposed  (10283): XInsta - Menu Click Listener Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
04-10 01:23:02.896 I/Xposed  (10283): XInsta - Profile Icon Click Listener Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
04-10 01:23:02.900 I/Xposed  (10283): XInsta - Profile Icon Click Listener Class - com.instagram.profile.fragment.fx
04-10 01:23:02.914 I/Xposed  (10283): XInsta - Search Tag Hook Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.v.b.b.b
04-10 01:23:02.923 I/Xposed  (10283): XInsta - Search Location Hook Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.v.b.d.d
04-10 01:23:02.930 I/Xposed  (10283): XInsta - Search Username Hook Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.v.a.c.b
04-10 01:23:02.937 I/Xposed  (10283): XInsta - Search Top Hook Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.v.b.e.m
04-10 01:23:02.943 I/Xposed  (10283): XInsta - Share Class Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
04-10 01:23:02.947 I/Xposed  (10283): XInsta - Share Class - com.instagram.feed.q.b.ad
04-10 01:23:07.821 ?/SENTINEL_TAG(10502): SENTINEL_MSG_LIBCUTILS

**Comment by iHelp101** [comment]
For some reason your error log is missing the line that says the Instagram version you are using. Do you know the version you are using so I can check the hooks for it?

**Comment by brato-mo** [comment]
I have issue also. History is showing in search bar, it is off in options but it still shows it. Updated instagram today

**Comment by iHelp101** [comment]
Okay, I am working on the hooks now for some new versions that got uploaded to APKMirror. Hopefully one of these versions is the one you are using.
