### ISSUE TITLE
Facing a bug. [Multiple accounts]

### ISSUE THREAD

**Issue by agtpirrone** [iHelp101/XInsta#32]
I have two different accounts logged in my phone. Whenever I want to download a story, everything is fine if the app just started. But if afterwards I switch accounts, I can't download stories no more. I have to force quit Instagram. And try again. Then is okay. But if I switch accounts there's the error again. Everything else looks working good.

Here's my log. I don't know if there is a more complete version. This is what I got from the module (also, the only way I could read it was to share it to my Google drive.)

20180410_193407 - XInsta Initialized
20180410_193407 - Instagram Version Code: 99640911
20180410_193407 - Device Codename: Nexus 5X
20180410_193407 - Android Version: 6.0.1
20180410_193407 - XInsta Version 2.0.4
20180410_193411 - One2
20180410_193411 - Falling Back To New Video Method
20180410_193411 - Switch Link - Different Media Type
20180410_193411 - SD Request Received
20180410_193411 - Passed To XInsta
20180410_193412 - Download Error - java.net.ConnectException: failed to connect to instagram.faep12-1.fna.fbcdn.net/168.195.57.161 (port 443): connect failed: ECONNREFUSED (Connection refused)
20180410_193416 - Falling Back To New Video Method
20180410_193416 - Switch Link - Different Media Type
20180410_193416 - SD Request Received
20180410_193416 - Passed To XInsta
20180410_193417 - Download Error - java.net.ConnectException: failed to connect to instagram.faep12-1.fna.fbcdn.net/168.195.57.161 (port 443): connect failed: ECONNREFUSED (Connection refused)
20180410_193424 - ---------------------------
20180410_193424 - XInsta Initialized
20180410_193424 - Instagram Version Code: 99640911
20180410_193424 - Device Codename: Nexus 5X
20180410_193424 - Android Version: 6.0.1
20180410_193424 - XInsta Version 2.0.4
20180410_193525 - Falling Back To New Video Method
20180410_193525 - Switch Link - Different Media Type
20180410_193525 - SD Request Received
20180410_193525 - Passed To XInsta
20180410_193526 - Download Error - java.net.ConnectException: failed to connect to instagram.faep12-1.fna.fbcdn.net/168.195.57.161 (port 443): connect failed: ECONNREFUSED (Connection refused)
20180410_193546 - Falling Back To New Video Method
20180410_193546 - SD Request Received
20180410_193546 - Passed To XInsta
20180410_193548 - ---------------------------
20180410_193548 - XInsta Initialized
20180410_193548 - Instagram Version Code: 99640911
20180410_193548 - Device Codename: Nexus 5X
20180410_193548 - Android Version: 6.0.1
20180410_193548 - XInsta Version 2.0.4
20180410_193549 - Download Error - java.net.ConnectException: failed to connect to instagram.faep12-1.fna.fbcdn.net/168.195.57.161 (port 443): connect failed: ECONNREFUSED (Connection refused)

**Comment by iHelp101** [comment]
The error is out of my control. It is from the OS (Android) saying for some reason it can't connect to Instagram to download the requested content. I can only request Android opens and URL. If Android returns back that it's can't I have little if any control. I will look further into this, but network related issues are OS related.

Download Error - java.net.ConnectException: failed to connect to instagram.faep12-1.fna.fbcdn.net/168.195.57.161 (port 443): connect failed: ECONNREFUSED (Connection refused)

**Comment by agtpirrone** [comment]
Oh well, thanks for the quick response. Do you think is a Instagram version + android version related? I have had always Marshmallow with XInsta. The only thing that has changed its the Instagram version, and of course XInsta, which I maintain updated because you are doing a great job.

My phone is working laggy lately. I had to apply the Bootloop of death fix and so I only have 4 cores and everything got really slow. Maybe is related to phone performance?

**Comment by iHelp101** [comment]
I truly have no idea why you are having the issue. It is a returned message by the OS. XInsta, Instagram, and Xposed don't handle network connections (OS does). The returned messaged is saying the connection is refused. This overall means the connection to Instagram couldn't be made, but many factor go into this. I do see that you pass downloads to XInsta, which means it is likely not an Instagram issue related to switching accounts (Like API key change). 

So we know a valid URL is passed. The issue is just why is Android saying the connection is refused. Is it firewall based? Instagram actually refusing/blocking the connection? Etc? I tested this on a few of my test devices (Moto G, Nexus 5, and HTC Desire) and no had this issue yet. Does this issue always occurs or is it random?

**Comment by agtpirrone** [comment]
Just an update on this. I know the problem hasnt been properly adressed and its might even be a problem on my side. 
But, i have upgraded to Android Oreo again and havent experienced the issue on this version of android.
