### ISSUE TITLE
Please update the hooks 

### ISSUE THREAD

**Issue by LuneWalsh** [iHelp101/XInsta#33]
Instagram released a new version of the app again, and the download button is missing again

04-12 03:44:44.938 I/Xposed  (14108): XInsta - Instagram Version Code: 102625270
04-12 03:44:44.949 I/Xposed  (14108): XInsta - Device Codename: ASUS_Z012DC
04-12 03:44:44.956 I/Xposed  (14108): XInsta - Android Version: 8.0.0
04-12 03:44:44.964 I/Xposed  (14108): XInsta - XInsta Version 2.0.4
04-12 03:44:45.309 I/Xposed  (14108): XInsta - Hooks Fetched!
04-12 03:44:45.720 I/Xposed  (14108): XInsta - Experimental Hooks Set
04-12 03:44:48.304 I/Xposed  (14108): XInsta - Menu Click Listener Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
04-12 03:44:48.331 I/Xposed  (14108): XInsta - Pin Press Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.ee
04-12 03:44:48.337 I/Xposed  (14108): XInsta - Pin Press Class - com.instagram.feed.r.a.ee
04-12 03:44:48.347 I/Xposed  (14108): XInsta - Pin Press New Touch Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.ek
04-12 03:44:48.351 I/Xposed  (14108): XInsta - Pin Press New Touch Class - com.instagram.feed.r.a.ek
04-12 03:44:48.364 I/Xposed  (14108): XInsta - Pin Press New Long Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.ej
04-12 03:44:48.370 I/Xposed  (14108): XInsta - Pin Press New Long Class - com.instagram.feed.r.a.ej
04-12 03:44:48.377 I/Xposed  (14108): XInsta - Pin Press New New Long Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.ef
04-12 03:44:48.384 I/Xposed  (14108): XInsta - Pin Press New New Long Class - com.instagram.feed.r.a.ej
04-12 03:44:48.401 I/Xposed  (14108): XInsta - Share Class Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.b.ag
04-12 03:44:48.407 I/Xposed  (14108): XInsta - Share Class - com.instagram.feed.r.b.ag
04-12 03:44:48.421 I/Xposed  (14108): XInsta - Story Privacy Hook Failed - java.lang.NoSuchMethodError: com.instagram.reels.fragment.dg#O()#exact
04-12 03:44:48.426 I/Xposed  (14108): XInsta - Story Privacy Hook Class - com.instagram.reels.fragment.dg
04-12 03:44:48.430 I/Xposed  (14108): XInsta - Story Privacy Hook Hook - O
04-12 03:44:48.439 I/Xposed  (14108): XInsta - Forcing Media Class
04-12 03:45:02.657 I/Xposed  (14295): XInsta - XInsta Initialized
04-12 03:45:02.696 I/Xposed  (14295): XInsta - Instagram Version Code: 102625270
04-12 03:45:02.705 I/Xposed  (14295): XInsta - Device Codename: ASUS_Z012DC
04-12 03:45:02.715 I/Xposed  (14295): XInsta - Android Version: 8.0.0
04-12 03:45:02.727 I/Xposed  (14295): XInsta - XInsta Version 2.0.4
04-12 03:45:03.216 I/Xposed  (14295): XInsta - Hooks Fetched!
04-12 03:45:03.652 I/Xposed  (14295): XInsta - Experimental Hooks Set
04-12 03:45:06.092 I/Xposed  (14295): XInsta - Menu Click Listener Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
04-12 03:45:06.117 I/Xposed  (14295): XInsta - Pin Press Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.ee
04-12 03:45:06.121 I/Xposed  (14295): XInsta - Pin Press Class - com.instagram.feed.r.a.ee
04-12 03:45:06.129 I/Xposed  (14295): XInsta - Pin Press New Touch Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.ek
04-12 03:45:06.133 I/Xposed  (14295): XInsta - Pin Press New Touch Class - com.instagram.feed.r.a.ek
04-12 03:45:06.142 I/Xposed  (14295): XInsta - Pin Press New Long Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.ej
04-12 03:45:06.146 I/Xposed  (14295): XInsta - Pin Press New Long Class - com.instagram.feed.r.a.ej
04-12 03:45:06.157 I/Xposed  (14295): XInsta - Pin Press New New Long Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.ef
04-12 03:45:06.162 I/Xposed  (14295): XInsta - Pin Press New New Long Class - com.instagram.feed.r.a.ej
04-12 03:45:06.177 I/Xposed  (14295): XInsta - Share Class Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.b.ag
04-12 03:45:06.183 I/Xposed  (14295): XInsta - Share Class - com.instagram.feed.r.b.ag
04-12 03:45:06.197 I/Xposed  (14295): XInsta - Story Privacy Hook Failed - java.lang.NoSuchMethodError: com.instagram.reels.fragment.dg#O()#exact
04-12 03:45:06.203 I/Xposed  (14295): XInsta - Story Privacy Hook Class - com.instagram.reels.fragment.dg
04-12 03:45:06.210 I/Xposed  (14295): XInsta - Story Privacy Hook Hook - O
04-12 03:45:06.219 I/Xposed  (14295): XInsta - Forcing Media Class
04-12 03:45:06.549 I/Xposed  (14362): XInsta - XInsta Initialized
04-12 03:45:06.561 I/Xposed  (14362): XInsta - Instagram Version Code: 102625270
04-12 03:45:06.568 I/Xposed  (14362): XInsta - Device Codename: ASUS_Z012DC
04-12 03:45:06.574 I/Xposed  (14362): XInsta - Android Version: 8.0.0
04-12 03:45:06.580 I/Xposed  (14362): XInsta - XInsta Version 2.0.4

**Comment by iHelp101** [comment]
The hooks have been updated to support this version.
