### ISSUE TITLE
Instagram freeze

### ISSUE THREAD

**Issue by jizzy002** [iHelp101/XInsta#37]
Instagram freezes while trying to open a sub menu in direct messages (delete converastion etc.)

**Comment by iHelp101** [comment]
I got a report of this issue from another user. If this when long pressing media/text in DM's? Can you provide a logcat?

**Comment by jizzy002** [comment]
While long pressing media,text,conversations in DM.
i will provide a logcat soon

**Comment by iHelp101** [comment]
Hello, I wanted to follow-up with you. Any luck getting a logcat of this crash/freezing?

**Comment by jizzy002** [comment]
Sorry for waiting here is a full logcat.
[logcat.txt](https://github.com/iHelp101/XInsta/files/1959076/logcat.txt)

**Comment by iHelp101** [comment]
This has been resolved and will be in the next update.

**Comment by jizzy002** [comment]
Tested today just by accident, long press in DM works again fully
