### ISSUE TITLE
Search history failed to hide 

### ISSUE THREAD

**Issue by woeijiunn88** [iHelp101/XInsta#41]
It seems failed to hide the search history even I selected disable search history option.

**Comment by iHelp101** [comment]
Please attach your XInsta error log or Xposed error log. That way I can test XInsta on the specific Instagram version you are using.

**Comment by iHelp101** [comment]
XInsta 2.0.5 resolves this issue. Please re-open this issue if you still have issues after updating.

**Comment by woeijiunn88** [comment]
@iHelp101 omg forgot reply this

**Comment by woeijiunn88** [comment]
@iHelp101 i will try then:smile:
