### ISSUE TITLE
Profile picture download

### ISSUE THREAD

**Issue by jizzy002** [iHelp101/XInsta#47]
While trying to download profile picture the Xinsta error popup comes up.
Running XInsta 2.0.5 (not test version)
and Instagram 47.0.0.16.96

**Comment by RiadReyBouazza** [comment]
Same issue here , sent an email with an attached log right after it crashed on me , same versions as this , I hope it gets fixed

**Comment by iHelp101** [comment]
Give this APK a try for me please. 

https://drive.google.com/file/d/1w4QtRLkPVxkJoFpf19GbqkpYpWGK1iT9/view?usp=drivesdk

**Comment by RiadReyBouazza** [comment]
Dude I am really sorry I received your email late because I didn't have
Gmail I just recovered from a soft brick
But you are truly amazing , the test version you sent me works great
Downloaded the profile picture straight on , I will do more testing for you
and let you know , you rock bro keep it up
Thank you very much

**Comment by iHelp101** [comment]
A zoom feature for profile icons? If you long press/hold a profile icon (In profile menu that shows number of followers, following, etc.) it will open a large view of the users profile icon. You can pinch to zoom like a gallery in this view.

**Comment by RiadReyBouazza** [comment]
More like a zoom feature for pictures and videos on the feed and stories ,
there's already an app that offers that and an Xposed module too but the
development of it is slow and it is still buggy n I would like to have all
my mods in one spot just like how xinsta is Rich of mods
But that was just an example , would like to see other features like some
theming ? Maybe hiding the seen ? The online status ? Etc
More exciting stuff , but either way this app is already awesome as it is ,
those are just suggestions to stimulate your creativity cause you seem to
be a skillful Dev.

**Comment by jizzy002** [comment]
Works with your version.
I was 2 days off didn't had any acess to a proper internet conmection

**Comment by achozex** [comment]
having the same issue 

log: https://drive.google.com/open?id=1-edwvEUxkk6JfF45cTf-Wxu1WPU7insS


I tried the apk that you attached here and it works now
