### ISSUE TITLE
Download Button 

### ISSUE THREAD

**Issue by LuneWalsh** [iHelp101/XInsta#48]
20180601_033401 - XInsta Initialized
20180601_033401 - Instagram Version Code: 111152037
20180601_033401 - Device Codename: ASUS_Z012DC
20180601_033401 - Android Version: 8.0.0
20180601_033401 - XInsta Version 2.0.5
20180601_033403 - Hooks Fetched!
20180601_033404 - Experimental Hooks Set
20180601_033404 -  Experimental Hook Failed - com.instagram.feed.comments
20180601_033406 - ---------------------------
20180601_033406 - XInsta Initialized
20180601_033406 - Instagram Version Code: 111152037
20180601_033406 - Device Codename: ASUS_Z012DC
20180601_033406 - Android Version: 8.0.0
20180601_033406 - XInsta Version 2.0.5
20180601_033407 - Hooks Fetched!
20180601_033408 - Experimental Hooks Set
20180601_033408 -  Experimental Hook Failed - com.instagram.feed.comments
20180601_033417 - GOt it: {"a":"https:\/\/scontent.cdninstagram.com\/vp\/34f246c33edfaf607812049875e64f4c\/5BB9CE25\/t51.2885-19\/s150x150\/25025959_868756379970631_5350290569362931712_n.jpg","bc":"{\"dt\":0}","c":"post","sound":"default","i":"https:\/\/scontent.cdninstagram.com\/vp\/c62290061bc4b0d172d35612f9f371d4\/5B139653\/t51.2885-15\/e35\/32858593_200261513938242_2832829766946521088_n.jpg","SuppressBadge":"1","m":"gym.legends acabou de publicar um vídeo.","collapse_key":"post","s":"2964025446","u":204115507,"PushNotifID":"56d8e7bba9a20Hc2a8e33H56d8ec5509cf2H49","pi":"56d8e7bba9a20Hc2a8e33H56d8ec5509cf2H49","ig":"media?id=1791930537183939612_2964025446"}
20180601_034549 - ---------------------------
20180601_034549 - XInsta Initialized
20180601_034549 - Instagram Version Code: 111152037
20180601_034549 - Device Codename: ASUS_Z012DC
20180601_034549 - Android Version: 8.0.0
20180601_034549 - XInsta Version 2.0.5
20180601_034550 - Hooks Fetched!
20180601_034550 - Experimental Hooks Set
20180601_034550 -  Experimental Hook Failed - com.instagram.feed.comments
20180601_034735 - ---------------------------
20180601_034735 - XInsta Initialized
20180601_034735 - Instagram Version Code: 111152037
20180601_034735 - Device Codename: ASUS_Z012DC
20180601_034735 - Android Version: 8.0.0
20180601_034735 - XInsta Version 2.0.5
20180601_034736 - Hooks Fetched!
20180601_034736 - Experimental Hooks Set
20180601_034736 -  Experimental Hook Failed - com.instagram.feed.comments
20180601_034740 - GOt it: {"a":"https:\/\/scontent.cdninstagram.com\/vp\/43e8c0dc50f7b13aed6270097fede54b\/5BC167C8\/t51.2885-19\/s150x150\/30829526_170405027116560_8976101505379598336_n.jpg","bc":"{\"dt\":0}","c":"post","sound":"default","i":"https:\/\/scontent.cdninstagram.com\/vp\/f1388ad1f6d7493d1008af794bfbf957\/5BB3E46B\/t51.2885-15\/e35\/32933499_254515371961411_8084847464487583744_n.jpg","SuppressBadge":"1","m":"alecnysten acabou de publicar uma foto.","collapse_key":"post","s":"38110492","u":204115507,"PushNotifID":"56d8eabff76edHc2a8e33H56d8ef59579bfH49","pi":"56d8eabff76edHc2a8e33H56d8ef59579bfH49","ig":"media?id=1791936407734710498_38110492"}
20180601_034740 - ---------------------------
20180601_034740 - XInsta Initialized
20180601_034740 - Instagram Version Code: 111152037
20180601_034740 - Device Codename: ASUS_Z012DC
20180601_034740 - Android Version: 8.0.0
20180601_034740 - XInsta Version 2.0.5
20180601_034740 - Hooks Fetched!
20180601_034741 - Experimental Hooks Set
20180601_034741 -  Experimental Hook Failed - com.instagram.feed.comments
20180601_035048 - ---------------------------
20180601_035048 - XInsta Initialized
20180601_035048 - Instagram Version Code: 111152037
20180601_035048 - Device Codename: ASUS_Z012DC
20180601_035048 - Android Version: 8.0.0
20180601_035048 - XInsta Version 2.0.5
20180601_035049 - Hooks Fetched!
20180601_035049 - Experimental Hooks Set
20180601_035049 -  Experimental Hook Failed - com.instagram.feed.comments

Thanks for the update, we all love you Girl or Boy xD

**Comment by Mashirosiki** [comment]
谢谢分享
