### ISSUE TITLE
App crashes.

### ISSUE THREAD

**Issue by sjhackic** [iHelp101/XInsta#49]
Instagram App keeps on crashing as i install this module. Tested this on Mi phones and Samsung Galaxy S8+ as well

**Comment by iHelp101** [comment]
Is this issue still occurring? Instagram had a bug with a few of their APK's related to crashing.

**Comment by woeijiunn88** [comment]
try update ur insta to latest ver 49.0.0.15.89, latest insta should not have problem

**Comment by RiadReyBouazza** [comment]
i also noticed that with those latest versions of instagram , the zoom for instagram module is force closing the app too , so if you have that enabled , turn it off and try
