### ISSUE TITLE
Instagram app crashing when trying to download a temporary picture in direct messages 

### ISSUE THREAD

**Issue by RiadReyBouazza** [iHelp101/XInsta#50]
using the latest version of xinsta v2.0.6 and latest instagram v49 
when i receive a temporary picture in dm's and try to download it , instagram crashes 
and seems to keep crashing till the timer of the picture is worn out ? 
i don't wait for it i just reboot the phone 
anyone experiencing this ?

**Comment by dxshxnt** [comment]
Same dude, is your one working now?
