### ISSUE TITLE
Download button missing. 

### ISSUE THREAD

**Issue by LuneWalsh** [iHelp101/XInsta#51]
Please check out my XInsta Error Log.

20180621_022912 - XInsta Initialized
20180621_022912 - Instagram Version Code: 113948109
20180621_022912 - Device Codename: ASUS_Z012DC
20180621_022912 - Android Version: 8.0.0
20180621_022912 - XInsta Version 2.0.6
20180621_022912 - Hooks Fetched!
20180621_022912 - Experimental Hooks Set
20180621_022912 -  Experimental Hook Failed - com.instagram.feed.comments
20180621_022915 - Comment Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180621_022915 - Comment Class: com.instagram.comments.c.p
20180621_022915 - Share Class Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180621_022915 - Share Class - com.instagram.feed.r.b.am
20180621_022915 - ---------------------------
20180621_022915 - XInsta Initialized
20180621_022915 - Instagram Version Code: 113948109
20180621_022915 - Device Codename: ASUS_Z012DC
20180621_022915 - Android Version: 8.0.0
20180621_022915 - XInsta Version 2.0.6
20180621_022916 - Hooks Fetched!
20180621_022916 - Experimental Hooks Set
20180621_022916 -  Experimental Hook Failed - com.instagram.feed.comments
20180621_022918 - Comment Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180621_022918 - Comment Class: com.instagram.comments.c.p
20180621_022918 - Share Class Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180621_022918 - Share Class - com.instagram.feed.r.b.am

My download button is missing, I already re-installed the XInsta and Cleaned the Instagram cache, please fix it.

**Comment by iHelp101** [comment]
Are you still facing this issue? If so, please disable Experimental Hooks.

**Comment by yanfedorov** [comment]
@iHelp101 same problem

# 20180628_185547 - XInsta Initialized 20180628_185547 - Instagram Version Code: 115211364 20180628_185547 - Device Codename: Redmi Note 4 20180628_185547 - Android Version: 6.0 20180628_185547 - XInsta Version 2.0.6 20180628_185548 - Hooks Fetched! 20180628_185549 - Share Class Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0 20180628_185549 - Share Class - com.instagram.feed.r.b.am 20180628_185550 - Stories Gallery Hook Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.common.gallery.m 20180628_185550 - Stories Gallery Hook Class - com.instagram.common.gallery.m 20180628_185554

**Comment by BurhanDanger** [comment]
I had similar problems with xinsta 2.0.6. Downgraded to original 2.0.5(provided by xposed download)

**Comment by iHelp101** [comment]
@BurhanDanger Did you as well have Experimental Hooks enabled?

**Comment by BurhanDanger** [comment]
I'm not sure, what I did was go to xinsta and clicked `update to xinsta 2.0.6` , then after update pressed GitHub just below Update Hooks. Didn't change any other settings.

**Comment by papuruth** [comment]
Same issue here
Instagram latest
Logs. 44:22.664 I/Xposed  (15936): XInsta - XInsta Initialized
08-30 22:44:22.686 I/Xposed  (15936): XInsta - Instagram Version Code: 122338251
08-30 22:44:22.693 I/Xposed  (15936): XInsta - Device Codename: Yureka Black
08-30 22:44:22.702 I/Xposed  (15936): XInsta - Android Version: 9.0
08-30 22:44:22.711 I/Xposed  (15936): XInsta - XInsta Version 2.0.8
08-30 22:44:23.719 I/Xposed  (15936): XInsta - Hooks Fetched!
08-30 22:44:27.222 I/Xposed  (15936): XInsta - Comment Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
08-30 22:44:27.231 I/Xposed  (15936): XInsta - Comment Class: X.3ix
08-30 22:44:27.244 I/Xposed  (15936): XInsta - Dialog Hook Failed: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
08-30 22:44:27.251 I/Xposed  (15936): XInsta - Dialog Hook Class: X.0YH
08-30 22:44:27.263 I/Xposed  (15936): XInsta - Direct OnClick Dialog Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
08-30 22:44:27.271 I/Xposed  (15936): XInsta - Discovery Class Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
08-30 22:44:27.278 I/Xposed  (15936): XInsta - Discovery Class - X.4Yy
08-30 22:44:27.286 I/Xposed  (15936): XInsta - Menu Click Listener Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
08-30 22:44:27.303 I/Xposed  (15936): XInsta - Follow List User Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
08-30 22:44:27.310 I/Xposed  (15936): XInsta - Follow List User Class - X.3lp
08-30 22:44:27.317 I/Xposed  (15936): XInsta - Follow List Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
08-30 22:44:27.325 I/Xposed  (15936): XInsta - Follow List Class - X.3lp
08-30 22:44:27.332 I/Xposed  (15936): XInsta - Like Hooks Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
08-30 22:44:27.339 I/Xposed  (15936): XInsta - Like Hook Class - X.1N0
08-30 22:44:27.350 I/Xposed  (15936): XInsta - Like Multi Hooks Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.r
08-30 22:44:27.357 I/Xposed  (15936): XInsta - Like Multi Hook Class - com.instagram.feed.r.a.r
08-30 22:44:27.364 I/Xposed  (15936): XInsta - Liked Post Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
08-30 22:44:27.371 I/Xposed  (15936): XInsta - Liked Post Class - X.508
08-30 22:44:27.378 I/Xposed  (15936): XInsta - Mini Feed OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
08-30 22:44:27.384 I/Xposed  (15936): XInsta - Mini Feed Class Failed - X.4bx
08-30 22:44:27.397 I/Xposed  (15936): XInsta - Pin Press Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
08-30 22:44:27.405 I/Xposed  (15936): XInsta - Pin Press Class - X.16i
08-30 22:44:27.411 I/Xposed  (15936): XInsta - Pin Press New Touch Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
08-30 22:44:27.418 I/Xposed  (15936): XInsta - Pin Press New Touch Class - X.16n
08-30 22:44:27.429 I/Xposed  (15936): XInsta - Pin Press New Long Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.dl
08-30 22:44:27.437 I/Xposed  (15936): XInsta - Pin Press New Long Class - com.instagram.feed.r.a.dl
08-30 22:44:27.447 I/Xposed  (15936): XInsta - Pin Press New New Long Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
08-30 22:44:27.455 I/Xposed  (15936): XInsta - Pin Press New New Long Class - com.instagram.feed.r.a.dl
08-30 22:44:27.463 I/Xposed  (15936): XInsta - Profile Icon Click Listener Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
08-30 22:44:27.475 I/Xposed  (15936): XInsta - Profile Icon Click Listener Class - X.0b7
08-30 22:44:27.482 I/Xposed  (15936): XInsta - Profile Icon Long Press Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
08-30 22:44:27.490 I/Xposed  (15936): XInsta - Profile Icon Long Press Hook - X.1gP
08-30 22:44:27.547 I/Xposed  (15936): XInsta - Sponsored Post Hook Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
08-30 22:44:27.554 I/Xposed  (15936): XInsta - Sponsored Post Class - X.0sJ
08-30 22:44:27.569 I/Xposed  (15936): XInsta - Stories OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
08-30 22:44:27.579 I/Xposed  (15936): XInsta - Stories OnClick Class - X.56j
08-30 22:44:27.608 I/Xposed  (15936): XInsta - Story Privacy Hook Failed - java.lang.NoSuchMethodError: com.instagram.reels.fragment.ReelViewerFragment#n()#exact
08-30 22:44:27.614 I/Xposed  (15936): XInsta - Story Privacy Hook Class - com.instagram.reels.fragment.ReelViewerFragment
08-30 22:44:27.621 I/Xposed  (15936): XInsta - Story Privacy Hook Hook - n
08-30 22:44:27.628 I/Xposed  (15936): XInsta - TV Hooks Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
08-30 22:44:27.633 I/Xposed  (15936): XInsta - TV Hook Class - X.4j7
08-30 22:44:27.641 I/Xposed  (15936): XInsta - Video Like Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
08-30 22:44:27.647 I/Xposed  (15936): XInsta - Video Like Class - X.1MG
