### ISSUE TITLE
Instagram keeps crashing everytime I try to download from Instagram direct. 

### ISSUE THREAD

**Issue by dxshxnt** [iHelp101/XInsta#52]
So I updated my Instagram to the latest version (50.1.0.43.119) and Xinsta (2.0.6). It was working fine before updating, I could download all the posts sent to me on Instagram direct. But now everytime I try to download a picture sent to me on direct, Instagram crashes right after I tap download. I tried updating hooks, downgrading my Instagram as well as Xinsta. So far no good. I uninstalled it, rebooted, reinstalled, it still doesn't work. I can download other things with no issues, it only crashes when I try to download from my Instagram direct messages. How do I solve it? Thanks for the help.

**Comment by dxshxnt** [comment]
I did try it out. Although the app doesn't crash anymore when I hit on the download option in the direct messages but it shows, Xinsta error. In the logs, by what I understood it shows, hooks invalid although all my hooks are up to date.

**Comment by dxshxnt** [comment]
I can provide the logs if they are required.

**Comment by iHelp101** [comment]
Yes, can you attach your error log? If it is version 52 of the new Instagram alpha it is using new obfuscation, which is proving tricky to counter. In these versions Instagram throws 15,000+ files in a single folder. They are only doing this on alpha builds for some reason.

**Comment by dxshxnt** [comment]
https://www.dropbox.com/s/bwnwwl64purn6gg/error?dl=0

**Comment by dxshxnt** [comment]
Here is the Xinsta error log. https://www.dropbox.com/s/bwnwwl64purn6gg/error.txt?dl=0

**Comment by dxshxnt** [comment]
And no, it's not version 52. I am using the one I mentioned on the post. That's the lastest update available on Google play.

**Comment by dxshxnt** [comment]
Hopefully you can fix it soon.

**Comment by dxshxnt** [comment]
Any fixes?

**Comment by dxshxnt** [comment]
Any response?

**Comment by iHelp101** [comment]
I am not having much luck with this and with the new changes with obfuscation I am working on getting direct downloads working again. It is going to take time. It is not clear where Instagram is storing this content at the moment.
