### ISSUE TITLE
Stories timer

### ISSUE THREAD

**Issue by jizzy002** [iHelp101/XInsta#54]
Story timer is broken after newest 50.0.X update, and long press onto profile picture, didn't notice any bigger issues more than that. If any logs are needed i will provide them.

**Comment by iHelp101** [comment]
Thank you for the information. I will be off work in a few hours and work on updating the hooks.

**Comment by dxshxnt** [comment]
Thank you.

**Comment by jizzy002** [comment]
Works like a charm, keep up the good work
