### ISSUE TITLE
Freezing and Crashing all the time

### ISSUE THREAD

**Issue by Hunchengli** [iHelp101/XInsta#56]
I'm using Samsung Note 5 with Instagram 49.0.0.18.95 and xInsta 2.0.6

Instagram has been freezing on story, lagging severely and crashing all the time when xInsta module is on.

What's activate on my xInsta:
Push Notification Download
Copy Comment on Tap
Video Likes Count
Story Privacy (I need this, so turning it off wouldn't be my choice)

I have read up on other issues on your Github and if Story Privacy is the cause and you have no way to solve it then leave this issue aside.

**Comment by Hunchengli** [comment]
It's disabled. Never used it.

**Comment by iHelp101** [comment]
Resolved in future update.
