### ISSUE TITLE
Don't work last version of instagram 

### ISSUE THREAD

**Issue by erkin98** [iHelp101/XInsta#58]

**Comment by exhelios** [comment]
Same here

**Comment by grota** [comment]
had to restart instagram a couple of times before it started working

**Comment by jizzy002** [comment]
Hooks not working on Instagram 55.0.0.12.79 but working on version 54.0.0.14.82

**Comment by jizzy002** [comment]
@jizzy002 Temporary solution is to downgrade your app and disable auto updates till new hook update i think

**Comment by iHelp101** [comment]
I will update the hooks in a few hours. It is going to be manual hook updating, which can take an hour or so. I am at work at the moment, so I can't dedicate an hour yet to getting the new hooks.
