### ISSUE TITLE
Problems with version of Instagram 53.0.0.12.84

### ISSUE THREAD

**Issue by LuneWalsh** [iHelp101/XInsta#60]
20180709_124432 - XInsta Initialized
20180709_124432 - Instagram Version Code: 116441973
20180709_124432 - Device Codename: ASUS_Z012DC
20180709_124432 - Android Version: 8.0.0
20180709_124432 - XInsta Version 2.0.6
20180709_124432 - Hooks Fetched!
20180709_124433 - Comment Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124433 - Comment Class: X.4Nt
20180709_124433 - Date Failed2 - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124433 - Date Failed2 Class - X.0tV
20180709_124433 - Dialog Hook Failed: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124433 - Dialog Hook Class: X.0ob
20180709_124433 - Direct OnClick Dialog Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124433 - Discovery Class Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: X.5bx
20180709_124433 - Discovery Class - X.5bx
20180709_124433 - Menu Click Listener Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124433 - Follow List User Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124433 - Follow List User Class - X.2Iy
20180709_124433 - Follow List Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124433 - Follow List Class - X.2Iy
20180709_124433 - Like Hooks Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124433 - Like Hook Class - X.3TP
20180709_124433 - Like Multi Hooks Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.r
20180709_124433 - Like Multi Hook Class - com.instagram.feed.r.a.r
20180709_124433 - Liked Post Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124433 - Liked Post Class - X.53z
20180709_124433 - Mini Feed OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124433 - Mini Feed Class Failed - X.4cl
20180709_124433 - Pin Press Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124433 - Pin Press Class - X.4bL
20180709_124433 - Pin Press New Touch Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124433 - Pin Press New Touch Class - X.4bR
20180709_124433 - Pin Press New Long Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.dl
20180709_124433 - Pin Press New Long Class - com.instagram.feed.r.a.dl
20180709_124433 - Pin Press New New Long Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124433 - Pin Press New New Long Class - com.instagram.feed.r.a.dl
20180709_124433 - Profile Icon Click Listener Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124433 - Profile Icon Click Listener Class - X.55V
20180709_124433 - Profile Icon Long Press Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124433 - Profile Icon Long Press Hook - X.51W
20180709_124433 - Sponsored Post Hook Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124433 - Sponsored Post Class - X.4tA
20180709_124433 - Stories OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124433 - Stories OnClick Class - X.5BI
20180709_124433 - Stories Timer Failed - java.lang.NoSuchMethodError: com.instagram.reels.fragment.ReelViewerFragment#Fm()#exact
20180709_124433 - Useragent Hook Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124433 - Forcing Media Class
20180709_124434 - ---------------------------
20180709_124434 - XInsta Initialized
20180709_124434 - Instagram Version Code: 116441973
20180709_124434 - Device Codename: ASUS_Z012DC
20180709_124434 - Android Version: 8.0.0
20180709_124434 - XInsta Version 2.0.6
20180709_124435 - ---------------------------
20180709_124435 - XInsta Initialized
20180709_124435 - Instagram Version Code: 116441973
20180709_124435 - Device Codename: ASUS_Z012DC
20180709_124435 - Android Version: 8.0.0
20180709_124435 - XInsta Version 2.0.6
20180709_124435 - Hooks Fetched!
20180709_124435 - Hooks Fetched!
20180709_124436 - Comment Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124436 - Comment Class: X.4Nt
20180709_124436 - Date Failed2 - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124436 - Date Failed2 Class - X.0tV
20180709_124436 - Dialog Hook Failed: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124436 - Dialog Hook Class: X.0ob
20180709_124436 - Direct OnClick Dialog Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124436 - Discovery Class Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: X.5bx
20180709_124436 - Comment Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124436 - Discovery Class - X.5bx
20180709_124436 - Comment Class: X.4Nt
20180709_124436 - Menu Click Listener Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124436 - Date Failed2 - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124436 - Follow List User Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124436 - Date Failed2 Class - X.0tV
20180709_124436 - Follow List User Class - X.2Iy
20180709_124436 - Dialog Hook Failed: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124436 - Follow List Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124436 - Dialog Hook Class: X.0ob
20180709_124436 - Follow List Class - X.2Iy
20180709_124436 - Like Hooks Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124436 - Direct OnClick Dialog Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124436 - Like Hook Class - X.3TP
20180709_124436 - Discovery Class Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: X.5bx
20180709_124436 - Discovery Class - X.5bx
20180709_124436 - Like Multi Hooks Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.r
20180709_124436 - Menu Click Listener Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124436 - Like Multi Hook Class - com.instagram.feed.r.a.r
20180709_124436 - Follow List User Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124436 - Liked Post Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124436 - Follow List User Class - X.2Iy
20180709_124436 - Liked Post Class - X.53z
20180709_124436 - Mini Feed OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124436 - Follow List Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124436 - Mini Feed Class Failed - X.4cl
20180709_124436 - Follow List Class - X.2Iy
20180709_124436 - Like Hooks Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124436 - Like Hook Class - X.3TP
20180709_124436 - Pin Press Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124436 - Pin Press Class - X.4bL
20180709_124436 - Like Multi Hooks Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.r
20180709_124436 - Like Multi Hook Class - com.instagram.feed.r.a.r
20180709_124436 - Pin Press New Touch Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124436 - Liked Post Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124436 - Pin Press New Touch Class - X.4bR
20180709_124436 - Liked Post Class - X.53z
20180709_124436 - Pin Press New Long Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.dl
20180709_124436 - Mini Feed OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124436 - Pin Press New Long Class - com.instagram.feed.r.a.dl
20180709_124436 - Mini Feed Class Failed - X.4cl
20180709_124436 - Pin Press New New Long Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124436 - Pin Press New New Long Class - com.instagram.feed.r.a.dl
20180709_124436 - Profile Icon Click Listener Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124436 - Pin Press Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124436 - Profile Icon Click Listener Class - X.55V
20180709_124436 - Pin Press Class - X.4bL
20180709_124436 - Pin Press New Touch Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124436 - Profile Icon Long Press Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124436 - Pin Press New Touch Class - X.4bR
20180709_124436 - Profile Icon Long Press Hook - X.51W
20180709_124436 - Pin Press New Long Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.dl
20180709_124436 - Pin Press New Long Class - com.instagram.feed.r.a.dl
20180709_124436 - Pin Press New New Long Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124436 - Pin Press New New Long Class - com.instagram.feed.r.a.dl
20180709_124436 - Profile Icon Click Listener Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124436 - Profile Icon Click Listener Class - X.55V
20180709_124436 - Sponsored Post Hook Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124436 - Profile Icon Long Press Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124436 - Sponsored Post Class - X.4tA
20180709_124436 - Profile Icon Long Press Hook - X.51W
20180709_124436 - Stories OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124436 - Stories OnClick Class - X.5BI
20180709_124436 - Stories Timer Failed - java.lang.NoSuchMethodError: com.instagram.reels.fragment.ReelViewerFragment#Fm()#exact
20180709_124436 - Useragent Hook Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124436 - Forcing Media Class
20180709_124436 - Sponsored Post Hook Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124436 - Sponsored Post Class - X.4tA
20180709_124436 - Stories OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124436 - Stories OnClick Class - X.5BI
20180709_124436 - Stories Timer Failed - java.lang.NoSuchMethodError: com.instagram.reels.fragment.ReelViewerFragment#Fm()#exact
20180709_124436 - Useragent Hook Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124436 - Forcing Media Class
20180709_124447 - ---------------------------
20180709_124447 - XInsta Initialized
20180709_124447 - Instagram Version Code: 116441973
20180709_124447 - Device Codename: ASUS_Z012DC
20180709_124447 - Android Version: 8.0.0
20180709_124447 - XInsta Version 2.0.6
20180709_124447 - Hooks Fetched!
20180709_124448 - Comment Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124448 - Comment Class: X.4Nt
20180709_124448 - Date Failed2 - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124448 - Date Failed2 Class - X.0tV
20180709_124448 - Dialog Hook Failed: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124448 - Dialog Hook Class: X.0ob
20180709_124448 - Direct OnClick Dialog Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124448 - Discovery Class Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: X.5bx
20180709_124448 - Discovery Class - X.5bx
20180709_124448 - Menu Click Listener Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124448 - Follow List User Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124448 - Follow List User Class - X.2Iy
20180709_124448 - Follow List Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124448 - Follow List Class - X.2Iy
20180709_124448 - Like Hooks Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124448 - Like Hook Class - X.3TP
20180709_124448 - Like Multi Hooks Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.r
20180709_124448 - Like Multi Hook Class - com.instagram.feed.r.a.r
20180709_124448 - Liked Post Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124448 - Liked Post Class - X.53z
20180709_124448 - Mini Feed OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124448 - Mini Feed Class Failed - X.4cl
20180709_124448 - Pin Press Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124448 - Pin Press Class - X.4bL
20180709_124448 - Pin Press New Touch Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124448 - Pin Press New Touch Class - X.4bR
20180709_124448 - Pin Press New Long Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.dl
20180709_124448 - Pin Press New Long Class - com.instagram.feed.r.a.dl
20180709_124448 - Pin Press New New Long Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124448 - Pin Press New New Long Class - com.instagram.feed.r.a.dl
20180709_124448 - Profile Icon Click Listener Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124448 - Profile Icon Click Listener Class - X.55V
20180709_124448 - Profile Icon Long Press Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124448 - Profile Icon Long Press Hook - X.51W
20180709_124448 - Sponsored Post Hook Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124448 - Sponsored Post Class - X.4tA
20180709_124448 - Stories OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124448 - Stories OnClick Class - X.5BI
20180709_124448 - Stories Timer Failed - java.lang.NoSuchMethodError: com.instagram.reels.fragment.ReelViewerFragment#Fm()#exact
20180709_124448 - Useragent Hook Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124448 - Forcing Media Class
20180709_124451 - ---------------------------
20180709_124451 - XInsta Initialized
20180709_124451 - Instagram Version Code: 116441973
20180709_124451 - Device Codename: ASUS_Z012DC
20180709_124451 - Android Version: 8.0.0
20180709_124451 - XInsta Version 2.0.6
20180709_124452 - Hooks Fetched!
20180709_124453 - Comment Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124453 - Comment Class: X.4Nt
20180709_124453 - Date Failed2 - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124453 - Date Failed2 Class - X.0tV
20180709_124453 - Dialog Hook Failed: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124453 - Dialog Hook Class: X.0ob
20180709_124453 - Direct OnClick Dialog Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124453 - Discovery Class Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: X.5bx
20180709_124453 - Discovery Class - X.5bx
20180709_124453 - Menu Click Listener Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124453 - Follow List User Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124453 - Follow List User Class - X.2Iy
20180709_124453 - Follow List Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124453 - Follow List Class - X.2Iy
20180709_124453 - Like Hooks Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124453 - Like Hook Class - X.3TP
20180709_124453 - Like Multi Hooks Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.r
20180709_124453 - Like Multi Hook Class - com.instagram.feed.r.a.r
20180709_124453 - Liked Post Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124453 - Liked Post Class - X.53z
20180709_124453 - Mini Feed OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124453 - Mini Feed Class Failed - X.4cl
20180709_124453 - Pin Press Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124453 - Pin Press Class - X.4bL
20180709_124453 - Pin Press New Touch Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124453 - Pin Press New Touch Class - X.4bR
20180709_124453 - Pin Press New Long Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.dl
20180709_124453 - Pin Press New Long Class - com.instagram.feed.r.a.dl
20180709_124453 - Pin Press New New Long Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124453 - Pin Press New New Long Class - com.instagram.feed.r.a.dl
20180709_124453 - Profile Icon Click Listener Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124453 - Profile Icon Click Listener Class - X.55V
20180709_124453 - Profile Icon Long Press Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124453 - Profile Icon Long Press Hook - X.51W
20180709_124453 - Sponsored Post Hook Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124453 - Sponsored Post Class - X.4tA
20180709_124453 - Stories OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124453 - Stories OnClick Class - X.5BI
20180709_124453 - Stories Timer Failed - java.lang.NoSuchMethodError: com.instagram.reels.fragment.ReelViewerFragment#Fm()#exact
20180709_124453 - Useragent Hook Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180709_124453 - Forcing Media Class

**Comment by iHelp101** [comment]
The hooks have been updated to support this version.
