### ISSUE TITLE
Download Failed

### ISSUE THREAD

**Issue by jizzy002** [iHelp101/XInsta#61]
Everything fails to download

**Comment by iHelp101** [comment]
Instagram is now targetting Android API 25. API 24 added a rule regarding intents passing file URI's to other applications. This is actually due the notification complete notification when clicked opening the gallery (Have to pass file URI). Give this APK a try for me.

https://drive.google.com/open?id=1bQo0PMMqcjR8ScrqQgYgGrQBa0vL4Nhn

**Comment by yanfedorov** [comment]
@iHelp101 I had problemes too ("Download" button missed) , but i reinstalled latest version of the Xinsta, rebooted my phone, cleared Instagram's cache and now all works fine (nearly).
```
20180715_183225 - XInsta Initialized 20180715_183225 - Instagram Version Code: 116756948 20180715_183225 - Device Codename: Redmi Note 4 20180715_183225 - Android Version: 6.0 20180715_183225 - XInsta Version 2.0.7 20180715_183225 - Like Multi Hooks Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.r 20180715_183226 - Like Multi Hook Class - com.instagram.feed.r.a.r 20180715_183226 - Pin Press New Long Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.dl 20180715_183226 - Pin Press New Long Class - com.instagram.feed.r.a.dl 20180715_183226 - Hi: X.511
```

**Comment by Pr0G4m3r** [comment]
@iHelp101 The download/notification works again just fine thx👌

**Comment by jizzy002** [comment]
Works fine.

**Comment by higgs0x00** [comment]
Just coming in to say that the apk a few posts above also works for me.  Thank you for all your work on this.

**Comment by jizzy002** [comment]
Couple of hooks working and some not again, not a problem but instagram is going a little bit too fast with these updates

**Comment by jizzy002** [comment]
Hooks failing again after new update

**Comment by steven7851** [comment]
IGTV download fail
Instagram 54.0.0.14.82 (117539) + XInsta 2.0.8

**Comment by jizzy002** [comment]
I will close the issue because it's has been fixed
