### ISSUE TITLE
Alguna Comunidad

### ISSUE THREAD

**Issue by makeins29** [iHelp101/XInsta#68]
Alguna Comunidad para estar informado?

**Comment by makeins29** [comment]
Hi, twitter?

**Comment by makeins29** [comment]
Do they have a Twitter account or somewhere to stay informed? to know which version is compatible with Xinsta

**Comment by marcosfiniano** [comment]
Hola,

Acabo de firmar la petición de "Samsung: Stop selling us inferior Exynos
phones!" y me encantaría que me ayudaras sumando tu firma.

Nuestro objetivo es llegar a 35,000 firmas y necesitamos más apoyo. Para
obtener más información y firmar la petición puedes abrir el siguiente link:

http://chng.it/LsLhQxKNhJ

¡Gracias!
Marcos
