### ISSUE TITLE
Some Hooks Break and Sponsorship Posts Are Not Blocked

### ISSUE THREAD

**Issue by acsway878787** [iHelp101/XInsta#69]
### Xposed Error Log
```
I/Xposed  (21842): XInsta - XInsta Initialized
I/Xposed  (21842): XInsta - Instagram Version Code: 119875229
I/Xposed  (21842): XInsta - Device Codename: ASUS_T00N
I/Xposed  (21842): XInsta - Android Version: 6.0.1
I/Xposed  (21842): XInsta - XInsta Version 2.0.8
I/Xposed  (21842): XInsta - Like Multi Hooks Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.r
I/Xposed  (21842): XInsta - Like Multi Hook Class - com.instagram.feed.r.a.r
I/Xposed  (21842): XInsta - Pin Press New Long Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.dl
I/Xposed  (21842): XInsta - Pin Press New Long Class - com.instagram.feed.r.a.dl
I/Xposed  (21842): XInsta - Pin Press New New Long Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
I/Xposed  (21842): XInsta - Pin Press New New Long Class - com.instagram.feed.r.a.dl
I/Xposed  (21842): XInsta - Story Privacy Hook Failed - java.lang.NoSuchMethodError: com.instagram.reels.fragment.ReelViewerFragment#jdfj34()#exact
I/Xposed  (21842): XInsta - Story Privacy Hook Class - com.instagram.reels.fragment.ReelViewerFragment
I/Xposed  (21842): XInsta - Story Privacy Hook Hook - jdfj34
```
### Sponsorship Posts Are Not Blocked
Even though I switched the "Hide Partnership Posts" option on, they still appear in both stories and normal posts (like the picture below).
![In stories](https://i.imgur.com/44JUqe8.png)

**Comment by iHelp101** [comment]
I am looking into this further. Sponsorship post in stories can not be blocked. They have the sponsor tag, but use a special view. However, normal feed post should be blocked/hidden.

**Comment by acsway878787** [comment]
@iHelp101 Thanks in advance. If you need to test anything, I'll be very glad to help.
By the way, is the github hook update function break again? I couldn't update the hook you updated 2 days ago by XInsta itself, but manual copy those hooks and paste worked fine.

**Comment by acsway878787** [comment]
The picture of sponsorship posts in normal feed posts are blocked, but their discriptions and comments are still exist, which look like this:
![Pic](https://i.imgur.com/Zrqtm9S.jpg)

**Comment by acsway878787** [comment]
There are another type: The ads of apps which have "Download" option with color under the picture.
![Pic](https://i.imgur.com/VNSTAuy.jpg)

**Comment by iHelp101** [comment]
XInsta has to have the first ad scrolled past (Due to how views are loaded by Instagram). If you scroll past the ad and then back up is the ad still present?

**Comment by acsway878787** [comment]
Yes, they still come out, but at a low frequency. And at the most time those post won't show up pictures, like the picture above.

**Comment by iHelp101** [comment]
Fixed in future update.
