### ISSUE TITLE
Version 60.x and above breaks compatibility 

### ISSUE THREAD

**Issue by abhinavprateek** [iHelp101/XInsta#72]
Hey,

Unable to use Xinsta with any of the version from 60.x
Will send the xposed and dmesg log if you want 

One question through, have you stopped support for Xinsta coz not seeing any more commits.

**Comment by georgeravenholm** [comment]
there was literally a commit from 8 days ago when u posted this lole

**Comment by papuruth** [comment]
Same here download button disappeared on version 61
