### ISSUE TITLE
The app won't work on newer versions of Instagram here's the error 

### ISSUE THREAD

**Issue by LuneWalsh** [iHelp101/XInsta#75]
20180909_163604 - XInsta Initialized
20180909_163605 - Instagram Version Code: 123103748
20180909_163605 - Device Codename: ASUS_Z012DC
20180909_163605 - Android Version: 8.0.0
20180909_163605 - XInsta Version 2.0.8
20180909_163605 - Hooks Fetched!
20180909_163606 - Comment Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163606 - Comment Class: X.3u3
20180909_163606 - Date Failed2 - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163606 - Date Failed2 Class - X.0X4
20180909_163606 - Dialog Hook Failed: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163606 - Dialog Hook Class: X.0YF
20180909_163606 - Direct OnClick Dialog Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163606 - Discovery Class Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163606 - Discovery Class - X.4gq
20180909_163606 - Menu Click Listener Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163606 - Follow List User Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163606 - Follow List User Class - X.3y7
20180909_163606 - Follow List Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163606 - Follow List Class - X.3y7
20180909_163606 - Like Hooks Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163606 - Like Hook Class - X.1Mq
20180909_163606 - Like Multi Hooks Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.r
20180909_163606 - Like Multi Hook Class - com.instagram.feed.r.a.r
20180909_163606 - Liked Post Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163606 - Liked Post Class - X.55p
20180909_163606 - Mini Feed OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163606 - Mini Feed Class Failed - X.4il
20180909_163606 - Pin Press Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163606 - Pin Press Class - X.16Z
20180909_163606 - Pin Press New Touch Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163606 - Pin Press New Touch Class - X.16e
20180909_163606 - Pin Press New Long Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.dl
20180909_163606 - Pin Press New Long Class - com.instagram.feed.r.a.dl
20180909_163606 - Pin Press New New Long Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163606 - Pin Press New New Long Class - com.instagram.feed.r.a.dl
20180909_163606 - Profile Icon Click Listener Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163606 - Profile Icon Click Listener Class - X.0b4
20180909_163606 - Profile Icon Long Press Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163606 - Profile Icon Long Press Hook - X.1g0
20180909_163606 - Sponsored Post Hook Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163606 - Sponsored Post Class - X.0sC
20180909_163606 - Stories OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163606 - Stories OnClick Class - X.5CX
20180909_163606 - Stories Timer Failed - java.lang.NoSuchMethodError: com.instagram.reels.fragment.ReelViewerFragment#g()#exact
20180909_163606 - TV Hooks Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163606 - TV Hook Class - X.4pM
20180909_163606 - Video Like Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163606 - Video Like Class - X.1M6
20180909_163639 - ---------------------------
20180909_163639 - XInsta Initialized
20180909_163639 - Instagram Version Code: 123103748
20180909_163639 - Device Codename: ASUS_Z012DC
20180909_163639 - Android Version: 8.0.0
20180909_163639 - XInsta Version 2.0.8
20180909_163639 - Hooks Fetched!
20180909_163640 - Comment Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163640 - Comment Class: X.3u3
20180909_163640 - Date Failed2 - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163640 - Date Failed2 Class - X.0X4
20180909_163640 - Dialog Hook Failed: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163640 - Dialog Hook Class: X.0YF
20180909_163640 - Direct OnClick Dialog Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163640 - Discovery Class Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163640 - Discovery Class - X.4gq
20180909_163640 - Menu Click Listener Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163640 - Follow List User Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163640 - Follow List User Class - X.3y7
20180909_163640 - Follow List Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163640 - Follow List Class - X.3y7
20180909_163640 - Like Hooks Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163640 - Like Hook Class - X.1Mq
20180909_163640 - Like Multi Hooks Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.r
20180909_163640 - Like Multi Hook Class - com.instagram.feed.r.a.r
20180909_163640 - Liked Post Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163640 - Liked Post Class - X.55p
20180909_163640 - Mini Feed OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163640 - Mini Feed Class Failed - X.4il
20180909_163640 - Pin Press Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163640 - Pin Press Class - X.16Z
20180909_163640 - Pin Press New Touch Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163640 - Pin Press New Touch Class - X.16e
20180909_163640 - Pin Press New Long Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.dl
20180909_163640 - Pin Press New Long Class - com.instagram.feed.r.a.dl
20180909_163640 - Pin Press New New Long Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163640 - Pin Press New New Long Class - com.instagram.feed.r.a.dl
20180909_163640 - Profile Icon Click Listener Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163640 - Profile Icon Click Listener Class - X.0b4
20180909_163640 - Profile Icon Long Press Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163640 - Profile Icon Long Press Hook - X.1g0
20180909_163640 - Sponsored Post Hook Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163640 - Sponsored Post Class - X.0sC
20180909_163640 - Stories OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163640 - Stories OnClick Class - X.5CX
20180909_163640 - Stories Timer Failed - java.lang.NoSuchMethodError: com.instagram.reels.fragment.ReelViewerFragment#g()#exact
20180909_163640 - TV Hooks Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163640 - TV Hook Class - X.4pM
20180909_163640 - Video Like Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163640 - Video Like Class - X.1M6
20180909_163641 - ---------------------------
20180909_163641 - XInsta Initialized
20180909_163641 - Instagram Version Code: 123103748
20180909_163641 - ---------------------------
20180909_163641 - Device Codename: ASUS_Z012DC
20180909_163641 - XInsta Initialized
20180909_163641 - Android Version: 8.0.0
20180909_163641 - Instagram Version Code: 123103748
20180909_163641 - XInsta Version 2.0.8
20180909_163641 - Device Codename: ASUS_Z012DC
20180909_163641 - Android Version: 8.0.0
20180909_163641 - XInsta Version 2.0.8
20180909_163641 - Hooks Fetched!
20180909_163641 - Hooks Fetched!
20180909_163642 - Comment Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Comment Class: X.3u3
20180909_163642 - Date Failed2 - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Date Failed2 Class - X.0X4
20180909_163642 - Dialog Hook Failed: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Dialog Hook Class: X.0YF
20180909_163642 - Direct OnClick Dialog Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Discovery Class Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Comment Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Discovery Class - X.4gq
20180909_163642 - Comment Class: X.3u3
20180909_163642 - Menu Click Listener Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Date Failed2 - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Follow List User Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Date Failed2 Class - X.0X4
20180909_163642 - Follow List User Class - X.3y7
20180909_163642 - Dialog Hook Failed: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Dialog Hook Class: X.0YF
20180909_163642 - Follow List Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Follow List Class - X.3y7
20180909_163642 - Direct OnClick Dialog Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Like Hooks Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Like Hook Class - X.1Mq
20180909_163642 - Discovery Class Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Discovery Class - X.4gq
20180909_163642 - Like Multi Hooks Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.r
20180909_163642 - Menu Click Listener Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Like Multi Hook Class - com.instagram.feed.r.a.r
20180909_163642 - Liked Post Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Follow List User Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Liked Post Class - X.55p
20180909_163642 - Follow List User Class - X.3y7
20180909_163642 - Mini Feed OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Follow List Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Mini Feed Class Failed - X.4il
20180909_163642 - Follow List Class - X.3y7
20180909_163642 - Like Hooks Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Pin Press Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Like Hook Class - X.1Mq
20180909_163642 - Pin Press Class - X.16Z
20180909_163642 - Like Multi Hooks Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.r
20180909_163642 - Pin Press New Touch Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Pin Press New Touch Class - X.16e
20180909_163642 - Like Multi Hook Class - com.instagram.feed.r.a.r
20180909_163642 - Liked Post Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Pin Press New Long Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.dl
20180909_163642 - Liked Post Class - X.55p
20180909_163642 - Pin Press New Long Class - com.instagram.feed.r.a.dl
20180909_163642 - Mini Feed OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Pin Press New New Long Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Mini Feed Class Failed - X.4il
20180909_163642 - Pin Press New New Long Class - com.instagram.feed.r.a.dl
20180909_163642 - Profile Icon Click Listener Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Pin Press Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Profile Icon Click Listener Class - X.0b4
20180909_163642 - Pin Press Class - X.16Z
20180909_163642 - Profile Icon Long Press Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Pin Press New Touch Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Profile Icon Long Press Hook - X.1g0
20180909_163642 - Pin Press New Touch Class - X.16e
20180909_163642 - Pin Press New Long Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.feed.r.a.dl
20180909_163642 - Pin Press New Long Class - com.instagram.feed.r.a.dl
20180909_163642 - Pin Press New New Long Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Pin Press New New Long Class - com.instagram.feed.r.a.dl
20180909_163642 - Sponsored Post Hook Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Profile Icon Click Listener Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Sponsored Post Class - X.0sC
20180909_163642 - Profile Icon Click Listener Class - X.0b4
20180909_163642 - Stories OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Profile Icon Long Press Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Stories OnClick Class - X.5CX
20180909_163642 - Profile Icon Long Press Hook - X.1g0
20180909_163642 - Stories Timer Failed - java.lang.NoSuchMethodError: com.instagram.reels.fragment.ReelViewerFragment#g()#exact
20180909_163642 - TV Hooks Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - TV Hook Class - X.4pM
20180909_163642 - Sponsored Post Hook Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Sponsored Post Class - X.0sC
20180909_163642 - Video Like Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Video Like Class - X.1M6
20180909_163642 - Stories OnClick Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Stories OnClick Class - X.5CX
20180909_163642 - Stories Timer Failed - java.lang.NoSuchMethodError: com.instagram.reels.fragment.ReelViewerFragment#g()#exact
20180909_163642 - TV Hooks Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - TV Hook Class - X.4pM
20180909_163642 - Video Like Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180909_163642 - Video Like Class - X.1M6

**Comment by iHelp101** [comment]
The hooks have been updated. Here is a test APK as well for some other issues. 

https://drive.google.com/open?id=1m_AwxL0PGfmHFKz0pg5udRape6R9IX4h

**Comment by LuneWalsh** [comment]
What I do now?

**Comment by gokulraj3** [comment]
Please do something...

**Comment by iHelp101** [comment]
I am creating an issue that will be for new Instagram version hook issues. That way it can be monitored easily as new version come out.
