### ISSUE TITLE
Poor quality of downloaded photos and videos

### ISSUE THREAD

**Issue by madox398** [iHelp101/XInsta#76]
Hi, I have a problem with the quality of downloaded photos and videos - they have almost a half reduced resolution - 640x800 (originally 1080x1350). I tested Force High Resolution and this doesn't help.
I tested:
-XInsta 2.0.7 and XInsta 2.0.8
-Instagram 58.0.0.12.73 and 43.0.0.10.97.
Android KitKat
Any advice?

**Comment by iHelp101** [comment]
What device are you using?

**Comment by madox398** [comment]
Sony Xperia E4g

**Comment by silver2004** [comment]
+1 on that, i have only 750x750px images downloaded, enabling/disabling "force high resolution" makes no change, i checked the same picture on the computer and it has higher resolution, so it gets limited.. My device is Xiaomi Redmi 3

**Comment by iHelp101** [comment]
Fixed in next update.
