### ISSUE TITLE
Watch Viewers of Story dont work 

### ISSUE THREAD

**Issue by moops44** [iHelp101/XInsta#79]
Like the title say, i cant watch the Viewers from my Storys anymore
IG Ver. 63.0.0.17.94, I'm also on the latest Hook

**Comment by hsinankirdar** [comment]
There can be some problem. XInsta firstly allows you to download media. After that, if some one updates all hooks, you can use all features.

**Comment by moops44** [comment]
> There can be some problem. XInsta firstly allows you to download media. After that, if some one updates all hooks, you can use all features.

Kardesim I know the functions of XInsta i use it for long time 

I overplayed my backup from IG Ver. 62.0.0.19.93
Watching Story Viewers worked for some time ( all other functions Work ) ,
then the Watch Viewer function stopped again, 
Im here to report an issue, that the devs can take a look bout my problem

**Comment by iHelp101** [comment]
Can you provide a screen recording or screenshot of this issue? I am not sure what you mean by watch viewers function. Thanks you.

**Comment by iHelp101** [comment]
Fixed in next update.
