### ISSUE TITLE
Direct

### ISSUE THREAD

**Issue by xbzd** [iHelp101/XInsta#84]
Hi
I have a weird issue with directs, sometimes I can't open messages at all, the only work around is downgrading insta. for a few days it works normally but then the issue appears again.
Have this problem with almost all insta versions (v49 to v72 132081645)
My brother's insta (132081645) with latest xinsta everything works flawlessly.
Just wanted to share this issue with you.
Thank you for your great module
[log.txt](https://github.com/iHelp101/XInsta/files/2637131/log.txt)
[Insta_Modal.txt](https://github.com/iHelp101/XInsta/files/2637086/Insta_Modal.txt)

**Comment by iHelp101** [comment]
Sorry to hear about this issue. Direct exist in two form. The first is regular direct messages that can be view anytime. Direct disappearing messages can only be view a few times and then eventually disappear. Which is the issue with? Also, are both you and you brother using the same model device? I wonder if it is a specific device/ROM that encounters this issue. Thank you.
