### ISSUE TITLE
TaiChi Support

### ISSUE THREAD

**Issue by HeyItsJono** [iHelp101/XInsta#87]
I was wondering if you would consider adding support for [TaiChi](https://github.com/tiann/EXposed/releases/tag/3.4.1) or [VirtualXposed](https://github.com/android-hacker/VirtualXposed/releases/tag/0.16.1). This would allow compatability with Android 9 (Pie), which would be amazing for those of us with phones that ship with Pie! Thanks!

**Comment by 0rimura** [comment]
Hi I'm new to github and I'm using xinsta. 
I did install the latest Instagram app by the latest xinsta apk doesn't work it doesn't show the download mode in the 3 dot icon

**Comment by iHelp101** [comment]
I am working on getting this. I have VirtualXposed working with a test version, but I had to isolate two hooks that are causing a crash. It may be a limitation of VirtualXposed that I have to disable these two hooks. They are resource related, so it may be the issue.

**Comment by HeyItsJono** [comment]
> I am working on getting this. I have VirtualXposed working with a test version, but I had to isolate two hooks that are causing a crash. It may be a limitation of VirtualXposed that I have to disable these two hooks. They are resource related, so it may be the issue.

Thank you for looking into it!!

**Comment by iHelp101** [comment]
Fixed in next update.
