### ISSUE TITLE
Compatibility List

### ISSUE THREAD

**Issue by Dancger** [iHelp101/XInsta#90]
Would be nice, if the is a list for XInsta Version <==> Instagram Version. Always need to try and test around 20 versions, until it works..

**Comment by jizzy002** [comment]
Compare the last hook number (1399065) with the apk version from apkmirror they should be always the same, if they the same hooks should always work

**Comment by Dancger** [comment]
Nice trick, thanks! Latest Hook: 1399065 => [Instagram 78.0.0.11.104 (139906)](https://www.apkmirror.com/apk/instagram/instagram-instagram/instagram-instagram-78-0-0-11-104-139906-release/)

**Comment by bmrd92** [comment]
Okay, I cannot get basically anything to work on x insta. Latest version.. using Ed exposed magisk Android pie etc. The only thing that works is downloading an image. Can anyone provide

1. What exact version of Instagram is needed

2. How exactly you updated the hooks (entire procedure from start to finish, literally everything) 

3. What features do, and do not work!

Thanks

**Comment by bmrd92** [comment]
I've tried probably 15 versions of Messenger

**Comment by iHelp101** [comment]
I am working on a new hook version due to issues with ARMv7 and ARM64 hooks differences.
