### ISSUE TITLE
Important issue on IG 81

### ISSUE THREAD

**Issue by exodius48** [iHelp101/XInsta#91]
[Error.txt](https://github.com/iHelp101/XInsta/files/2898090/Error.txt)
I can diwnload photo , but when try to download video, it downloaded as photo, not video.

**Comment by exodius48** [comment]
@iHelp101 Update hooks for IG 82 pls


android:versionCode="143631575" android:versionName="82.0.0.13.119"

**Comment by iHelp101** [comment]
@exodius48 I updated the hooks and pushed them to Pastebin. I will continue further testing in the morning to make sure everything is working. If you work like to use the test hooks open XInsta -> Click Pastebin and reboot.

**Comment by exodius48** [comment]
@iHelp101 Didnt test on IG 81, but on IG 82 i updated hooks from pastebin > reboot. Download button still disappear. Im using Tai Chi 4.3.9 + XInsta 2.1.0 on android 9 pie

**Comment by exodius48** [comment]
[Error.txt](https://github.com/iHelp101/XInsta/files/2910222/Error.txt)
Ok, updated hooks from pastebin again this evening, download button appear & video download is normal ( downloaded as video not image)
Tested on IG 82 on MIUI 10 android 9 pie not rooted. Error.txt above is captured when opening IG 82. 
@iHelp101

**Comment by exodius48** [comment]
Update iasue:
On IG 82 download button appear on stories, but when i tap it, it report as spam, not download video/image. Then i tap report, IG crashed @iHelp101 

[Error.txt](https://github.com/iHelp101/XInsta/files/2910257/Error.txt)

**Comment by SwiftSilverYT** [comment]
I tried updating hooks with pastebin snd rebooting mu phone but videos still download as pictures

**Comment by exodius48** [comment]
> I tried updating hooks with pastebin snd rebooting mu phone but videos still download as pictures

Try to update to IG 82 stable. But stories download still broken

**Comment by exodius48** [comment]
android:versionCode="143631575" android:versionName="82.0.0.13.119"
@iHelp101 i dont know why, download button is disappear suddenly.

**Comment by exodius48** [comment]
@iHelp101 need update hooks, IG stable from playstsore

android:versionCode="144612598" android:versionName="83.0.0.20.111"

**Comment by exodius48** [comment]
@iHelp101 thx for updating the hooks. But i can't still download stories. Download button appear but when i tap it, it become report page. Then i tap report button, IG crash

**Comment by exodius48** [comment]
[Error.txt](https://github.com/iHelp101/XInsta/files/2944875/Error.txt)
Error file @iHelp101

**Comment by iHelp101** [comment]
Can you provide a screenshot of the download button/option? Instagram is testing a new dialog after you click the three dot icon and I am wondering if that is the issues you are having.

**Comment by exodius48** [comment]
@iHelp101 Here i send you screenrecord instead of Screenshot http://s000.tinyupload.com/index.php?file_id=23695288536806756210 . Also tap copy on comment not working, comment not copied. 
[Error.txt](https://github.com/iHelp101/XInsta/files/2946070/Error.txt)

**Comment by exodius48** [comment]
@iHelp101 Updated to IG 84 + Updated hooks from pastebin, but download button still disappear.
IG 84.0.0.21.105 build 145652094
Tai Chi version 5.1.0 https://github.com/taichi-framework/TaiChi/releases

**Comment by exodius48** [comment]
@iHelp101 IG 86 stable released, 86.0.0.24.87 build 147375143

**Comment by exodius48** [comment]
@iHelp101 Updated to IG 88.0.0.14.99 and hooks from pastebin & github, download button is appear, but when i click it, it become share button, does not download the image/video
[Error.txt](https://github.com/iHelp101/XInsta/files/3073265/Error.txt)
[Hooks.txt](https://github.com/iHelp101/XInsta/files/3073266/Hooks.txt)

**Comment by iHelp101** [comment]
@exodius48 Is this on specific types of downloads? Stories, profile, etc. Or all downloads have this issue?

**Comment by exodius48** [comment]
@iHelp101 Stories download become report spam, profile download is OK, image/video download from person that i've followed is become share

**Comment by exodius48** [comment]
Updated to IG 94, download working, stories privacy, tap comment to copy not working, pin save to download i select tap and hold seems not working too. @iHelp101 
[Error.txt](https://github.com/iHelp101/XInsta/files/3225315/Error.txt)
