### ISSUE TITLE
Android Pie multiple bug

### ISSUE THREAD

**Issue by Frksx** [iHelp101/XInsta#93]
Here is a list of bug i found on Pie with details.

- When instagram has storage access Xinsta download but no more notification from download.
If we remove instagram storage access there is a first failed download and there the notification appear and xinsta download the image anyway.
It appears Xinsta create a notification in the wrong channel.
In developer mode we can see "Failed to post notification on channel "null""

- Push notification auto download doesnt work anymore.

Here is information about device :
Android 9 Pie
Magisk, Edxposed and Xinsta 2.1.0, latest hook working.

Any other instamod apk don't have push auto download and dont let a notification to see what you downloaded, that is my fav features so i hope to get it fixed as soon as possible.
Thanks !

**Comment by iHelp101** [comment]
I am working on resolving this issue in the next update. I will provide a test APK shortly.

**Comment by iHelp101** [comment]
Fixed in next update.
