### ISSUE TITLE
Story Timer Removal feature

### ISSUE THREAD

**Issue by pain2theworld** [iHelp101/XInsta#94]
I'm unable to figure what this feature refers to. I've looked up for answers on XDA Forums and Google. Is anyone willing to answer what does "Story Timer Removal" feature refers to please?

**Comment by iHelp101** [comment]
Stories can be set to last for a specific duration and then go to the next story. This feature overrides that setting and keeps a story open until you click to advance to the next one or close the story.

**Comment by trinaldi** [comment]
Is this feature working?

**Comment by arlllk** [comment]
To me with 1553740 works perfectly

**Comment by trinaldi** [comment]
Huh...it's not working for me  It was working then I had to reinstall.

How exactly do I activate the mod? I've tried disable-reboot, enable-reboot

**Comment by arlllk** [comment]
Yo need to go to the Xposed App and from there activate the module. Then you go to XInsta options activate the option. But you need to make sure that you're using the correct Instagram version

On Fri, Jun 7, 2019 at 4:46 PM Tiago Rinaldi <notifications@github.com<mailto:notifications@github.com>> wrote:

Huh...it's not working for me It was working then I had to reinstall.

How exactly do I activate the mod? I've tried disable-reboot, enable-reboot

**Comment by trinaldi** [comment]
I'm using a version that was working before. I'm gonna retry.

**Comment by trinaldi** [comment]
Yeah, not working for me.

**Comment by iHelp101** [comment]
Fixed in next update.

**Comment by trinaldi** [comment]
Nice, thanks!

**Comment by trinaldi** [comment]
Not working
