### ISSUE TITLE
Hooks Update 

### ISSUE THREAD

**Issue by Poet145** [iHelp101/XInsta#95]
Hello. I'm running IG 90.0.0.18.110, on OP6T 9.0.3. Is there a hooks update available? Last update on here was 16 days ago and the current hooks stopped working last week. Can I rollback to a particular previous version of IG to get Xinsta working again (at least downloads)?

**Comment by iHelp101** [comment]
Open XInsta -> Click Pastebin and reboot. This should get this version for you. Pastebin is where I test hooks before I push them to GitHub.

**Comment by Poet145** [comment]
Going to test now. Will report back momentarily. Thanks for the quick response!

**Comment by Poet145** [comment]
I believe all hooks are working. I can confirm downloading (all, selections etc) images and video working. Stories timer working. Can't test hide story views, but all else seems functional. Thanks!

**Comment by iamdexter** [comment]
Where is the url to the pastebin, I try to download changing the default config but stills download the one from GitHub... Send it by private if needed. 

Thanks.

**Comment by iHelp101** [comment]
https://pastebin.com/raw/sTXbUFcx

**Comment by exodius48** [comment]
@iHelp101 My IG version 91.0.0.18.118 build 152367502 , updated hooks from pastebin don't work, download button disappear

**Comment by jizzy002** [comment]
> @iHelp101 My IG version 91.0.0.18.118 build 152367502 , updated hooks from pastebin don't work, download button disappear

Currently if you are on a higher DPI device hooks are broken, because they are only updated to version 152367**4** not 152367**5** so wait a little bit more till they get updated :)

**Comment by ayush7gl** [comment]
Please update hooks to version 93. Instagram v91 v92 v93 all not working.

**Comment by exodius48** [comment]
@iHelp101 I Updated IG to version 93 when i see new hooks on pastebin. But download button still disappear.
My IG version 93.1.0.19.102 build 154400383

**Comment by ayush7gl** [comment]
Please update hooks for instagram v98. There is no updtae after v93 please update.

**Comment by Poet145** [comment]
I second that request. I'm still running 93.1.0.19.102 for this very reason and although it allows me to download, there are security reasons and additional functionality that comes with updates and I'd like to be able to update. Is there anyway we can help locate the hooks?

**Comment by exodius48** [comment]
@ayush7gl @Poet145 Try update hooks from Pastebin. I see update on pastebin "1595266" which is build number of IG 98

**Comment by ayush7gl** [comment]
@exodius48 where can i see updates on pastebin. Please provide me a link.

**Comment by exodius48** [comment]
> 
> 
> @exodius48 where can i see updates on pastebin. Please provide me a link.

http://pastebin.com/raw/sTXbUFcx
