### ISSUE TITLE
Hook generation

### ISSUE THREAD

**Issue by Ristovski** [iHelp101/XInsta#97]
Could you disclose the method for hook update generation? I assume you use some kind of script.

It would be nice if people using the beta/alpha versions of Instagram could use XInsta as well without having to stay on stable and wait until XInsta has a new hooks update.

**Comment by jizzy002** [comment]
**Bump** for this one, i want to know how to pull the hooks and contribute to this module instead of just merging pastebin hooks

**Comment by iHelp101** [comment]
I made a Python script public about a year ago that I use for updating the hooks. Some of the hooks do require manual work to find them, but I will work better on documentation. I will also work on a better method of finding hooks. 

https://github.com/iHelp101/XInsta-Helper

**Comment by Ristovski** [comment]
Very nice, thanks!
